'use client';

import { useCallback, useEffect, useState } from 'react';
import { CHAVE_IDIOMA_PUBLICO, EVENTO_IDIOMA_PUBLICO, resolverIdiomaPublico, type IdiomaPublico } from './idioma-publico';
import { traducoesComplementares } from './traducoes-complementares';
import { traducoesEquipamentos } from './traducoes-equipamentos';

type Trio = readonly [portugues: string, ingles: string, alemao: string];

const textos = [
  ['Início', 'Home', 'Startseite'], ['Serviços', 'Services', 'Dienstleistungen'], ['Novidades no Centro', 'News from the Center', 'Neuigkeiten aus dem Zentrum'], ['Acontece no Centro', 'News from the Center', 'Aktuelles im Zentrum'], ['Equipamentos', 'Equipment', 'Ausrüstung'], ['Entrar', 'Sign in', 'Anmelden'], ['Solicitar orçamento', 'Request a quote', 'Angebot anfordern'], ['Menu', 'Menu', 'Menü'],
  ['Precisão para medir.', 'Precision to measure.', 'Präzision zum Messen.'], ['Inteligência para evoluir.', 'Intelligence to improve.', 'Intelligenz zur Weiterentwicklung.'], ['METROLOGIA QUE GERA CONHECIMENTO', 'METROLOGY THAT CREATES KNOWLEDGE', 'MESSTECHNIK, DIE WISSEN SCHAFFT'], ['Serviços de metrologia avançada com propostas transparentes, acompanhamento digital e conhecimento acumulado a cada projeto.', 'Advanced metrology services with transparent proposals, digital tracking and knowledge accumulated with every project.', 'Fortschrittliche Messtechnik mit transparenten Angeboten, digitaler Auftragsverfolgung und Wissen aus jedem Projekt.'], ['Conhecer serviços', 'Explore services', 'Dienstleistungen entdecken'], ['equipamentos disponíveis', 'available machines', 'verfügbare Maschinen'], ['idiomas disponíveis', 'available languages', 'verfügbare Sprachen'], ['acompanhamento digital', 'digital tracking', 'digitale Auftragsverfolgung'],
  ['DIFERENCIAL GLOBAL', 'GLOBAL DIFFERENCE', 'GLOBALER UNTERSCHIED'], ['Por que escolher o laboratório ZEISS?', 'Why choose the ZEISS laboratory?', 'Warum das ZEISS-Labor wählen?'], ['Integramos uma rede extremamente rara de centros de excelência, com estrutura avançada e atendimento próximo à indústria latino-americana.', 'We are part of an exceptionally rare network of centers of excellence, with advanced infrastructure close to Latin American industry.', 'Wir sind Teil eines außergewöhnlich seltenen Netzwerks von Kompetenzzentren mit moderner Infrastruktur für die lateinamerikanische Industrie.'], ['laboratórios como este no mundo', 'laboratories like this worldwide', 'vergleichbare Labore weltweit'], ['o único da América Latina', 'the only one in Latin America', 'das einzige in Lateinamerika'],
  ['ESTRUTURA REAL', 'REAL INFRASTRUCTURE', 'REALE INFRASTRUKTUR'], ['Um centro de excelência preparado para medir o que importa.', 'A center of excellence ready to measure what matters.', 'Ein Kompetenzzentrum, das misst, was zählt.'], ['O laboratório reúne medição por coordenadas, inspeção por raios X e digitalização óptica em um ambiente dedicado à precisão.', 'The laboratory brings together coordinate measurement, X-ray inspection and optical scanning in an environment dedicated to precision.', 'Das Labor vereint Koordinatenmesstechnik, Röntgenprüfung und optisches Scannen in einer auf Präzision ausgerichteten Umgebung.'], ['Conheça os equipamentos', 'Explore the equipment', 'Ausrüstung entdecken'],
  ['COMECE AGORA', 'START NOW', 'JETZT STARTEN'], ['Tem um desafio de medição?', 'Do you have a measurement challenge?', 'Haben Sie eine Messaufgabe?'], ['Conte o que você precisa. Nossa equipe analisa os dados e prepara uma proposta sob medida.', 'Tell us what you need. Our team analyzes the data and prepares a tailored proposal.', 'Beschreiben Sie Ihren Bedarf. Unser Team analysiert die Daten und erstellt ein passendes Angebot.'],
  ['Portal para gestão de serviços e conhecimento em orçamentação.', 'Portal for service management and quoting knowledge.', 'Portal für Dienstleistungsmanagement und Angebotswissen.'], ['Todos os direitos reservados.', 'All rights reserved.', 'Alle Rechte vorbehalten.'], ['Serviços e equipamentos', 'Services and equipment', 'Dienstleistungen und Ausrüstung'], ['Privacidade', 'Privacy', 'Datenschutz'], ['Contato', 'Contact', 'Kontakt'],
  ['Soluções organizadas por setor', 'Solutions organized by industry', 'Lösungen nach Branche'], ['ENCONTRE O SEU CONTEXTO', 'FIND YOUR CONTEXT', 'FINDEN SIE IHREN KONTEXT'], ['Escolha o cenário mais próximo da sua empresa. Os nomes técnicos continuam disponíveis, mas aparecem somente quando ajudam a explicar uma necessidade daquele setor.', 'Choose the scenario closest to your company. Technical names remain available, but appear only when they help explain an industry need.', 'Wählen Sie das Szenario, das Ihrem Unternehmen am nächsten kommt. Technische Begriffe erscheinen dort, wo sie den Branchenbedarf erklären.'], ['Serviços que podem fazer sentido', 'Services that may fit', 'Mögliche Dienstleistungen'], ['A combinação final depende da análise técnica da peça, do objetivo e dos arquivos enviados.', 'The final combination depends on a technical review of the part, the objective and the submitted files.', 'Die endgültige Kombination hängt von der technischen Prüfung des Bauteils, dem Ziel und den eingereichten Dateien ab.'],
  ['TECNOLOGIAS', 'TECHNOLOGIES', 'TECHNOLOGIEN'], ['Três áreas tecnológicas apoiam esse portfólio.', 'Three technology areas support this portfolio.', 'Drei Technologiebereiche tragen dieses Portfolio.'], ['CAPACIDADE', 'CAPABILITY', 'LEISTUNG'], ['Solicitar análise', 'Request an analysis', 'Analyse anfragen'], ['INFRAESTRUTURA ATUAL', 'CURRENT INFRASTRUCTURE', 'AKTUELLE INFRASTRUKTUR'], ['Seis equipamentos e aplicações complementares.', 'Six machines and complementary applications.', 'Sechs Maschinen und ergänzende Anwendungen.'], ['Capacidades e disponibilidade de cada equipamento são confirmadas pela equipe antes da proposta.', 'The team confirms the capabilities and availability of each machine before the proposal.', 'Leistungsumfang und Verfügbarkeit jeder Maschine werden vor dem Angebot vom Team bestätigt.'], ['Conhecer equipamento', 'Explore equipment', 'Maschine ansehen'], ['DEMANDA ABERTA', 'OPEN REQUEST', 'OFFENE ANFRAGE'], ['Seu desafio combina serviços ou exige outra abordagem?', 'Does your challenge combine services or require another approach?', 'Kombiniert Ihre Aufgabe mehrere Leistungen oder erfordert sie einen anderen Ansatz?'], ['Descreva livremente a necessidade, a peça, o objetivo e o resultado esperado. A equipe poderá indicar a combinação mais adequada de tecnologias e entregáveis.', 'Describe the need, part, objective and expected result. The team can recommend the most suitable combination of technologies and deliverables.', 'Beschreiben Sie Bedarf, Bauteil, Ziel und erwartetes Ergebnis. Das Team empfiehlt die passende Kombination aus Technologien und Ergebnissen.'], ['Criar solicitação personalizada', 'Create a custom request', 'Individuelle Anfrage erstellen'],
  ['Medição tridimensional', 'Coordinate measurement', 'Koordinatenmesstechnik'], ['Raios X industrial', 'Industrial X-ray', 'Industrielles Röntgen'], ['Digitalização óptica 3D', '3D optical scanning', 'Optisches 3D-Scannen'],
  ['O equipamento e seu papel no Centro', 'The machine and its role at the Center', 'Die Maschine und ihre Rolle im Zentrum'], ['Antes de solicitar', 'Before requesting', 'Vor der Anfrage'], ['Consultar referência técnica da ZEISS', 'View ZEISS technical reference', 'Technische ZEISS-Referenz ansehen'], ['Aplicações frequentes', 'Common applications', 'Häufige Anwendungen'], ['Capacidades', 'Capabilities', 'Leistungsumfang'], ['Medições e entregáveis', 'Measurements and deliverables', 'Messungen und Ergebnisse'], ['Diferenciais', 'Key advantages', 'Besondere Vorteile'], ['ANÁLISE TÉCNICA', 'TECHNICAL REVIEW', 'TECHNISCHE PRÜFUNG'], ['Confirme a melhor estratégia para sua peça.', 'Confirm the best strategy for your part.', 'Bestätigen Sie die beste Strategie für Ihr Bauteil.'], ['Envie dimensões, material, tolerâncias, quantidade, finalidade e, se possível, desenho ou modelo CAD. A equipe valida equipamento, preparação, prazo e entregáveis.', 'Send dimensions, material, tolerances, quantity, purpose and, if possible, a drawing or CAD model. The team validates the machine, preparation, lead time and deliverables.', 'Senden Sie Abmessungen, Material, Toleranzen, Menge, Zweck und möglichst eine Zeichnung oder ein CAD-Modell. Das Team prüft Maschine, Vorbereitung, Termin und Ergebnisse.'], ['Solicitar análise com este equipamento', 'Request an analysis with this machine', 'Analyse mit dieser Maschine anfragen'],
  ['Outro canal', 'Another channel', 'Weiterer Kontaktweg'], ['Também é possível enviar por e-mail', 'You can also submit by email', 'Sie können Ihre Anfrage auch per E-Mail senden'], ['Se preferir, descreva sua necessidade e envie os arquivos diretamente à equipe. Mensagens por e-mail não geram protocolo automaticamente; o laboratório fará a triagem e orientará o próximo passo.', 'If you prefer, describe your need and send files directly to the team. Email messages do not automatically create a tracking number; the laboratory will review them and advise the next step.', 'Beschreiben Sie bei Bedarf Ihre Aufgabe und senden Sie Dateien direkt an das Team. E-Mails erzeugen nicht automatisch eine Vorgangsnummer; das Labor prüft sie und informiert über den nächsten Schritt.'], ['Abrir aplicativo', 'Open email app', 'E-Mail-App öffnen'], ['Abrir Gmail', 'Open Gmail', 'Gmail öffnen'], ['Copiar', 'Copy', 'Kopieren'], ['Copiado', 'Copied', 'Kopiert'],
  ['Sobre esta demonstração', 'About this environment', 'Über diese Umgebung'], ['Finalidades previstas', 'Intended purposes', 'Vorgesehene Zwecke'], ['Acesso do cliente', 'Customer access', 'Kundenzugang'], ['Arquivos e inteligência artificial', 'Files and artificial intelligence', 'Dateien und künstliche Intelligenz'], ['Seus direitos e contato', 'Your rights and contact', 'Ihre Rechte und Kontakt'], ['Última atualização:', 'Last updated:', 'Letzte Aktualisierung:'],
  ['Minha área', 'My area', 'Mein Bereich'], ['Meus trabalhos', 'My work', 'Meine Aufträge'], ['Mensagens', 'Messages', 'Nachrichten'], ['Meu perfil', 'My profile', 'Mein Profil'], ['Sair', 'Sign out', 'Abmelden'], ['Trabalhos vinculados', 'Linked work', 'Verknüpfte Aufträge'], ['Em execução', 'In progress', 'In Bearbeitung'], ['Aguardando sua decisão', 'Awaiting your decision', 'Ihre Entscheidung steht aus'], ['Nova solicitação', 'New request', 'Neue Anfrage'], ['Pesquisar protocolo, serviço, empresa ou data', 'Search tracking number, service, company or date', 'Vorgangsnummer, Leistung, Unternehmen oder Datum suchen'], ['Todos os trabalhos', 'All work', 'Alle Aufträge'], ['Ativos', 'Active', 'Aktiv'], ['Concluídos', 'Completed', 'Abgeschlossen'], ['Mais recentes', 'Newest first', 'Neueste zuerst'], ['Mais antigos', 'Oldest first', 'Älteste zuerst'], ['Etapas do trabalho', 'Work stages', 'Auftragsphasen'], ['Arquivos da solicitação', 'Request files', 'Anfragedateien'], ['Andamento do serviço', 'Service progress', 'Auftragsfortschritt'], ['Enviar', 'Send', 'Senden'], ['Baixar', 'Download', 'Herunterladen'], ['Anexar', 'Attach', 'Anhängen'], ['Aceitar pré-proposta', 'Accept proposal', 'Angebot annehmen'], ['Recusar e solicitar revisão', 'Decline and request a revision', 'Ablehnen und Überarbeitung anfordern'], ['Cancelar', 'Cancel', 'Abbrechen'], ['Continuar', 'Continue', 'Fortfahren'], ['Proteção de dados', 'Data protection', 'Datenschutz'], ['Antes de acessar sua área', 'Before accessing your area', 'Vor dem Zugriff auf Ihren Bereich'],
  ['Solicitação salva na homologação', 'Request saved successfully', 'Anfrage erfolgreich gespeichert'], ['Vincular ao acompanhamento do Cliente', 'Open customer tracking', 'Kundenverfolgung öffnen'], ['Homologação persistente.', 'Persistent validation environment.', 'Persistente Validierungsumgebung.'], ['Você pode usar uma caixa de e-mail válida para receber acesso e recuperar a senha. Não inclua informações industriais confidenciais; os registros continuam isolados na origem de homologação.', 'You may use a valid email address to receive access and recover your password. Do not include confidential industrial information; records remain isolated in the validation environment.', 'Sie können eine gültige E-Mail-Adresse für Zugang und Passwortwiederherstellung verwenden. Geben Sie keine vertraulichen Industriedaten ein; alle Datensätze bleiben in der Validierungsumgebung isoliert.'],
  ['1. Você e sua empresa', '1. You and your company', '1. Sie und Ihr Unternehmen'], ['Nome completo', 'Full name', 'Vollständiger Name'], ['E-mail para o acesso Cliente', 'Email for customer access', 'E-Mail für den Kundenzugang'], ['Nome da empresa', 'Company name', 'Unternehmensname'], ['Telefone', 'Phone', 'Telefon'], ['Prazo de pagamento desejado', 'Preferred payment term', 'Gewünschtes Zahlungsziel'], ['dias', 'days', 'Tage'], ['Outro prazo', 'Other term', 'Anderes Zahlungsziel'], ['Informe o prazo desejado em dias', 'Enter the preferred term in days', 'Gewünschtes Zahlungsziel in Tagen'],
  ['2. O que você precisa?', '2. What do you need?', '2. Was benötigen Sie?'], ['Tipo de necessidade', 'Type of request', 'Art der Anfrage'], ['Selecione', 'Select', 'Auswählen'], ['Material da peça', 'Part material', 'Bauteilmaterial'], ['Outro material', 'Other material', 'Anderes Material'], ['Qual resultado você espera?', 'What result do you expect?', 'Welches Ergebnis erwarten Sie?'], ['Quantidade', 'Quantity', 'Menge'], ['Prazo desejado para o serviço', 'Desired service date', 'Gewünschter Fertigstellungstermin'], ['Descreva o desafio', 'Describe the challenge', 'Beschreiben Sie die Aufgabe'], ['3. Arquivos técnicos', '3. Technical files', '3. Technische Dateien'], ['Prepare PDF, imagem ou arquivo CAD', 'Prepare a PDF, image or CAD file', 'PDF, Bild oder CAD-Datei vorbereiten'], ['Na homologação, os arquivos permanecem no dispositivo até o acesso autenticado.', 'In the validation environment, files remain on your device until authenticated access.', 'In der Validierungsumgebung bleiben Dateien bis zum authentifizierten Zugriff auf Ihrem Gerät.'], ['Confirmo que compreendi o uso dos dados e aceito a', 'I understand how the data will be used and accept the', 'Ich verstehe die Datennutzung und akzeptiere die'], ['política de privacidade', 'privacy policy', 'Datenschutzerklärung'], ['Salvando…', 'Saving…', 'Wird gespeichert…'], ['Enviar solicitação', 'Submit request', 'Anfrage senden'],
  ['Digitalização e criação de modelo 3D', '3D digitization and model creation', '3D-Digitalisierung und Modellerstellung'], ['Medição e inspeção dimensional', 'Dimensional measurement and inspection', 'Maßprüfung und dimensionale Inspektion'], ['Inspeção interna sem destruir a peça', 'Internal inspection without damaging the part', 'Innenprüfung ohne Zerstörung des Bauteils'], ['Engenharia reversa e adequação técnica', 'Reverse engineering and technical adaptation', 'Reverse Engineering und technische Anpassung'], ['Análise de falha ou desgaste', 'Failure or wear analysis', 'Fehler- oder Verschleißanalyse'], ['Preciso de orientação para escolher', 'I need guidance to choose', 'Ich benötige Beratung bei der Auswahl'], ['Outra necessidade', 'Another request', 'Anderer Bedarf'],
  ['nome@empresa.com.br', 'name@company.com', 'name@unternehmen.de'], ['Formato da data: dd/mm/aaaa', 'Date format: mm/dd/yyyy', 'Datumsformat: TT.MM.JJJJ'],
  ['Indústria e processos produtivos', 'Industry and production processes', 'Industrie und Produktionsprozesse'], ['Automotivo e mobilidade', 'Automotive and mobility', 'Automobil und Mobilität'], ['Aeronáutico', 'Aerospace', 'Luftfahrt'], ['Ferramentaria e desenvolvimento de produto', 'Toolmaking and product development', 'Werkzeugbau und Produktentwicklung'],
  ['Escaneamento 3D e digitalização de peças', '3D scanning and part digitization', '3D-Scannen und Bauteildigitalisierung'], ['Engenharia reversa e reconstrução CAD', 'Reverse engineering and CAD reconstruction', 'Reverse Engineering und CAD-Rekonstruktion'], ['Nacionalização e desenvolvimento de componentes', 'Localization and component development', 'Lokalisierung und Komponentenentwicklung'], ['Metrologia avançada ZEISS e inspeção dimensional', 'Advanced ZEISS metrology and dimensional inspection', 'Fortschrittliche ZEISS-Messtechnik und Maßprüfung'], ['Comparação CAD × peça física', 'CAD-to-part comparison', 'CAD-Bauteil-Vergleich'], ['Mapa de desgaste', 'Wear mapping', 'Verschleißanalyse'], ['Tomografia industrial para inspeção interna não destrutiva', 'Industrial CT for non-destructive internal inspection', 'Industrielle CT zur zerstörungsfreien Innenprüfung'], ['Análise de falhas, quebras e anomalias', 'Failure, breakage and anomaly analysis', 'Analyse von Fehlern, Brüchen und Anomalien'], ['Estruturação de árvore de equipamentos e peças críticas', 'Equipment hierarchy and critical-part mapping', 'Strukturierung von Anlagen und kritischen Bauteilen'], ['Apoio na criação de almoxarifado virtual e biblioteca digital de peças', 'Support for virtual inventory and digital part libraries', 'Unterstützung für virtuelle Lager und digitale Bauteilbibliotheken'],
] as const satisfies readonly Trio[];

const todasAsTraducoes = [...textos, ...traducoesComplementares, ...traducoesEquipamentos] as const;
const mapas = Object.fromEntries((['pt-BR', 'en', 'de'] as const).map((idioma, indice) => [idioma, new Map(todasAsTraducoes.map((trio) => [trio[0], trio[indice]]))])) as Record<IdiomaPublico, Map<string, string>>;

export function traduzirTextoPublico(texto: string, idioma: IdiomaPublico) {
  return mapas[idioma].get(texto) ?? texto;
}

export function traduzirMensagemPublica(texto: string, idioma: IdiomaPublico) {
  const direta = traduzirTextoPublico(texto, idioma);
  if (direta !== texto || idioma === 'pt-BR') return direta;
  const formatoSolicitacao = texto.match(/^O formato de (.+) não é aceito\. Use PDF, imagem ou arquivo CAD\.$/);
  if (formatoSolicitacao) return `${traduzirTextoPublico('O formato de', idioma)} ${formatoSolicitacao[1]} ${traduzirTextoPublico('não é aceito. Use PDF, imagem ou arquivo CAD.', idioma)}`;
  const limiteSolicitacao = texto.match(/^(.+) excede o limite de (\d+) MB\.$/);
  if (limiteSolicitacao) return `${limiteSolicitacao[1]} ${traduzirTextoPublico('excede o limite de', idioma)} ${limiteSolicitacao[2]} MB.`;
  const formatoMensagem = texto.match(/^(.+): formato não permitido\.$/);
  if (formatoMensagem) return `${formatoMensagem[1]}: ${traduzirTextoPublico('formato não permitido.', idioma)}`;
  const limiteMensagem = texto.match(/^(.+): o limite por arquivo é 10 MB\.$/);
  if (limiteMensagem) return `${limiteMensagem[1]}: ${traduzirTextoPublico('o limite por arquivo é 10 MB.', idioma)}`;
  const etapa = texto.match(/^Etapa em andamento: (\d+)% concluída\.$/);
  if (etapa) return `${traduzirTextoPublico('Etapa em andamento:', idioma)} ${etapa[1]}% ${traduzirTextoPublico('concluída.', idioma)}`;
  const aceite = texto.match(/^(Registrado em .+?\. )(.+)$/);
  if (aceite) {
    const data = aceite[1].slice('Registrado em '.length, -2);
    return `${traduzirTextoPublico('Registrado em', idioma)} ${data}. ${traduzirTextoPublico(aceite[2], idioma)}`;
  }
  return texto;
}

export function possuiTraducaoPublica(texto: string, idioma: Exclude<IdiomaPublico, 'pt-BR'>) {
  return mapas[idioma].has(texto);
}

export function useIdiomaPublico() {
  const [idioma, setIdioma] = useState<IdiomaPublico>('pt-BR');
  useEffect(() => {
    const atualizar = (evento?: Event) => setIdioma(evento instanceof CustomEvent && evento.detail ? evento.detail as IdiomaPublico : resolverIdiomaPublico(window.location.href, window.localStorage.getItem(CHAVE_IDIOMA_PUBLICO)));
    atualizar(); window.addEventListener(EVENTO_IDIOMA_PUBLICO, atualizar); return () => window.removeEventListener(EVENTO_IDIOMA_PUBLICO, atualizar);
  }, []);
  return idioma;
}

export function useTraducaoPublica() {
  const idioma = useIdiomaPublico();
  const t = useCallback((texto: string) => traduzirTextoPublico(texto, idioma), [idioma]);
  const tm = useCallback((texto: string) => traduzirMensagemPublica(texto, idioma), [idioma]);
  return { idioma, t, tm };
}
