export type TrioTraducao = readonly [portugues: string, ingles: string, alemao: string];

export const traducoesComplementares = [
  ['Navegação principal', 'Main navigation', 'Hauptnavigation'],
  ['Abrir menu', 'Open menu', 'Menü öffnen'],
  ['Navegação em telas pequenas', 'Mobile navigation', 'Mobile Navigation'],
  ['carrossel', 'carousel', 'Karussell'],
  ['Selecionar mídia', 'Select media', 'Medium auswählen'],
  ['Carregando próxima mídia…', 'Loading next media…', 'Nächstes Medium wird geladen…'],
  ['Mídia anterior', 'Previous media', 'Vorheriges Medium'],
  ['Próxima mídia', 'Next media', 'Nächstes Medium'],
  ['Fotos e vídeos de', 'Photos and videos of', 'Fotos und Videos von'],
  ['Centro de Excelência em Metrologia SENAI ZEISS', 'SENAI ZEISS Metrology Center of Excellence', 'SENAI ZEISS Kompetenzzentrum für Messtechnik'],
  ['Estrutura do Centro', 'Center infrastructure', 'Infrastruktur des Zentrums'],
  ['Galeria do Centro de Excelência em Metrologia', 'Metrology Center of Excellence gallery', 'Galerie des Kompetenzzentrums für Messtechnik'],
  ['Apresentação em vídeo do Centro de Excelência em Metrologia SENAI ZEISS', 'Video presentation of the SENAI ZEISS Metrology Center of Excellence', 'Videopräsentation des SENAI ZEISS Kompetenzzentrums für Messtechnik'],
  ['Conheça as tecnologias disponíveis no Centro e encontre o caminho mais adequado para o seu desafio de medição.', 'Explore the technologies available at the Center and find the best approach for your measurement challenge.', 'Entdecken Sie die im Zentrum verfügbaren Technologien und finden Sie den passenden Weg für Ihre Messaufgabe.'],
  ['Privacidade e uso seguro', 'Privacy and safe use', 'Datenschutz und sichere Nutzung'],
  ['Diretrizes para o uso responsável e protegido do portal.', 'Guidelines for responsible and secure use of the portal.', 'Richtlinien für die verantwortungsvolle und sichere Nutzung des Portals.'],
  ['Conteúdo exibido em português porque esta tradução ainda não foi publicada.', 'This content is shown in Portuguese because this translation has not been published yet.', 'Dieser Inhalt wird auf Portugiesisch angezeigt, weil die Übersetzung noch nicht veröffentlicht wurde.'],

  ['Inspeção tátil ou multissensor de dimensões, forma e posição, com programação e relatórios técnicos.', 'Tactile or multisensor inspection of dimensions, form and position, including programming and technical reports.', 'Taktile oder Multisensor-Prüfung von Maß, Form und Lage einschließlich Programmierung und technischer Berichte.'],
  ['Investigação não destrutiva de estruturas internas, montagem, porosidade e outras descontinuidades.', 'Non-destructive investigation of internal structures, assembly, porosity and other discontinuities.', 'Zerstörungsfreie Untersuchung innerer Strukturen, Montagezustände, Porosität und weiterer Unregelmäßigkeiten.'],
  ['Captura de superfícies para inspeção, comparação nominal-real e reconstrução geométrica.', 'Surface capture for inspection, nominal-to-actual comparison and geometric reconstruction.', 'Oberflächenerfassung für Prüfung, Soll-Ist-Vergleich und geometrische Rekonstruktion.'],
  ['Inspeção radiográfica 2D', '2D radiographic inspection', '2D-Röntgenprüfung'],
  ['Análise técnica de falhas', 'Technical failure analysis', 'Technische Fehleranalyse'],
  ['Engenharia reversa e comparação CAD', 'Reverse engineering and CAD comparison', 'Reverse Engineering und CAD-Vergleich'],

  ['Captura da geometria de peças e conjuntos para gerar dados tridimensionais utilizáveis em inspeção, documentação e engenharia.', 'Capture of part and assembly geometry to generate three-dimensional data for inspection, documentation and engineering.', 'Erfassung der Geometrie von Bauteilen und Baugruppen zur Erzeugung dreidimensionaler Daten für Prüfung, Dokumentation und Konstruktion.'],
  ['Reconstrução de modelos digitais a partir da peça física, apoiando manutenção, reprodução, melhoria e documentação técnica.', 'Reconstruction of digital models from physical parts to support maintenance, reproduction, improvement and technical documentation.', 'Rekonstruktion digitaler Modelle aus physischen Bauteilen zur Unterstützung von Wartung, Nachfertigung, Verbesserung und technischer Dokumentation.'],
  ['Apoio técnico para compreender, documentar e desenvolver componentes equivalentes ou adaptados às necessidades da indústria.', 'Technical support to understand, document and develop equivalent components or components adapted to industrial needs.', 'Technische Unterstützung beim Verstehen, Dokumentieren und Entwickeln gleichwertiger oder an industrielle Anforderungen angepasster Komponenten.'],
  ['Medição de dimensões, forma, posição e geometrias complexas com tecnologias ZEISS e relatórios técnicos.', 'Measurement of dimensions, form, position and complex geometries using ZEISS technologies and technical reports.', 'Messung von Maß, Form, Lage und komplexen Geometrien mit ZEISS-Technologien und technischen Berichten.'],
  ['Comparação nominal-real para localizar, visualizar e quantificar desvios entre o projeto digital e o componente produzido.', 'Nominal-to-actual comparison to locate, visualize and quantify deviations between the digital design and the manufactured component.', 'Soll-Ist-Vergleich zur Lokalisierung, Visualisierung und Quantifizierung von Abweichungen zwischen digitalem Entwurf und gefertigtem Bauteil.'],
  ['Mapeamento de alterações geométricas e perda de material para apoiar diagnóstico, manutenção e acompanhamento de vida útil.', 'Mapping of geometric changes and material loss to support diagnostics, maintenance and service-life monitoring.', 'Erfassung geometrischer Veränderungen und von Materialverlust zur Unterstützung von Diagnose, Wartung und Lebensdauerüberwachung.'],
  ['Investigação de características internas sem seccionar a peça, conforme viabilidade técnica do material e da geometria.', 'Investigation of internal features without sectioning the part, subject to the technical feasibility of its material and geometry.', 'Untersuchung innerer Merkmale ohne Zerstörung des Bauteils, abhängig von der technischen Eignung von Material und Geometrie.'],
  ['Apoio metrológico à investigação de ocorrências, desvios e mecanismos de falha em componentes e conjuntos.', 'Metrology support for investigating incidents, deviations and failure mechanisms in components and assemblies.', 'Messtechnische Unterstützung bei der Untersuchung von Ereignissen, Abweichungen und Versagensmechanismen in Bauteilen und Baugruppen.'],
  ['Organização hierárquica de ativos, subconjuntos e componentes críticos para facilitar rastreabilidade e gestão técnica.', 'Hierarchical organization of assets, subassemblies and critical components to improve traceability and technical management.', 'Hierarchische Organisation von Anlagen, Unterbaugruppen und kritischen Komponenten für bessere Rückverfolgbarkeit und technische Verwaltung.'],
  ['Estruturação de um acervo digital de peças, modelos e informações técnicas para consulta, reposição e continuidade operacional.', 'Creation of a digital collection of parts, models and technical information for consultation, replacement and operational continuity.', 'Aufbau eines digitalen Bestands aus Bauteilen, Modellen und technischen Informationen für Recherche, Ersatz und Betriebskontinuität.'],

  ['Apoio a fábricas, plantas de processo e operações de manutenção que precisam medir, diagnosticar ou reproduzir componentes.', 'Support for factories, process plants and maintenance operations that need to measure, diagnose or reproduce components.', 'Unterstützung für Fabriken, Prozessanlagen und Instandhaltung, die Komponenten messen, diagnostizieren oder nachfertigen müssen.'],
  ['Alimentos, mineração, papel e celulose, bens de consumo e indústria de base.', 'Food, mining, pulp and paper, consumer goods and basic industries.', 'Lebensmittel, Bergbau, Zellstoff und Papier, Konsumgüter und Grundstoffindustrie.'],
  ['Inspeção, digitalização e comparação de componentes, conjuntos, ferramentas e protótipos do setor de mobilidade.', 'Inspection, digitization and comparison of components, assemblies, tools and prototypes in the mobility sector.', 'Prüfung, Digitalisierung und Vergleich von Komponenten, Baugruppen, Werkzeugen und Prototypen im Mobilitätssektor.'],
  ['Fabricantes, sistemistas, preparadores, custom shops e fornecedores de componentes.', 'Manufacturers, system suppliers, vehicle builders, custom shops and component suppliers.', 'Hersteller, Systemlieferanten, Fahrzeugbauer, Custom Shops und Komponentenlieferanten.'],
  ['Metrologia para componentes de alta complexidade, documentação dimensional, inspeção interna e apoio à engenharia.', 'Metrology for highly complex components, dimensional documentation, internal inspection and engineering support.', 'Messtechnik für hochkomplexe Komponenten, Maßdokumentation, Innenprüfung und Konstruktionsunterstützung.'],
  ['Fabricantes, manutenção aeronáutica e fornecedores de peças e subconjuntos.', 'Manufacturers, aircraft maintenance organizations and suppliers of parts and subassemblies.', 'Hersteller, Luftfahrtinstandhaltung und Lieferanten von Teilen und Unterbaugruppen.'],
  ['Um caminho direto para quem desenvolve moldes, dispositivos, protótipos ou precisa reconstruir geometrias existentes.', 'A direct path for teams developing molds, fixtures or prototypes, or reconstructing existing geometries.', 'Ein direkter Weg für Teams, die Formen, Vorrichtungen oder Prototypen entwickeln oder bestehende Geometrien rekonstruieren.'],
  ['Ferramentarias, usinagem, manufatura aditiva, engenharia e desenvolvimento de produto.', 'Toolmaking, machining, additive manufacturing, engineering and product development.', 'Werkzeugbau, Zerspanung, additive Fertigung, Konstruktion und Produktentwicklung.'],
  ['Operação metrológica no laboratório', 'Metrology operation in the laboratory', 'Messtechnischer Betrieb im Labor'],
  ['Medição dimensional no acervo autorizado do laboratório', 'Dimensional measurement from the laboratory’s authorized media collection', 'Maßprüfung aus dem freigegebenen Medienbestand des Labors'],
  ['Digitalização óptica no laboratório', 'Optical scanning in the laboratory', 'Optisches Scannen im Labor'],
  ['Digitalização óptica 3D no acervo autorizado do laboratório', '3D optical scanning from the laboratory’s authorized media collection', 'Optisches 3D-Scannen aus dem freigegebenen Medienbestand des Labors'],
  ['Tomografia industrial com o equipamento ZEISS BOSELLO MAX', 'Industrial X-ray inspection with the ZEISS BOSELLO MAX', 'Industrielle Röntgenprüfung mit der ZEISS BOSELLO MAX'],
  ['Tomografia industrial Bosello no acervo autorizado do laboratório', 'Bosello industrial X-ray inspection from the laboratory’s authorized media collection', 'Industrielle Bosello-Röntgenprüfung aus dem freigegebenen Medienbestand des Labors'],
  ['Máquina de medição por coordenadas no laboratório', 'Coordinate measuring machine in the laboratory', 'Koordinatenmessgerät im Labor'],
  ['Estrutura de metrologia dimensional do laboratório', 'Laboratory dimensional metrology infrastructure', 'Infrastruktur des Labors für dimensionelle Messtechnik'],

  ['Voltar ao site', 'Back to website', 'Zur Website'],
  ['Editar dados do perfil', 'Edit profile details', 'Profildaten bearbeiten'],
  ['Ex.: Analista da qualidade', 'E.g. Quality analyst', 'Z. B. Qualitätsanalyst/in'],
  ['Este campo descreve sua função profissional e não altera suas permissões de acesso.', 'This field describes your professional role and does not change your access permissions.', 'Dieses Feld beschreibt Ihre berufliche Funktion und ändert Ihre Zugriffsrechte nicht.'],
  ['Resumo dos trabalhos', 'Work summary', 'Auftragsübersicht'],
  ['Carregando acompanhamento…', 'Loading tracking information…', 'Auftragsverfolgung wird geladen…'],
  ['Registre a solicitação nesta área protegida. Ela já nascerá vinculada à sua empresa e aparecerá aqui imediatamente.', 'Submit the request in this protected area. It will be linked to your company and appear here immediately.', 'Erfassen Sie die Anfrage in diesem geschützten Bereich. Sie wird sofort Ihrem Unternehmen zugeordnet und hier angezeigt.'],
  ['Registrar novo trabalho', 'Create new work request', 'Neuen Auftrag anlegen'],
  ['peça(s)', 'part(s)', 'Bauteil(e)'],
  ['Quantidade não informada', 'Quantity not provided', 'Menge nicht angegeben'],
  ['Nenhum trabalho corresponde à pesquisa e aos filtros.', 'No work matches the search and filters.', 'Kein Auftrag entspricht der Suche und den Filtern.'],
  ['Ainda não emitida', 'Not issued yet', 'Noch nicht ausgestellt'],
  ['Será exibida após análise e publicação pela equipe.', 'It will be displayed after the team reviews and publishes it.', 'Sie wird nach Prüfung und Veröffentlichung durch das Team angezeigt.'],
  ['Pagamento desejado:', 'Preferred payment term:', 'Gewünschtes Zahlungsziel:'],
  ['Condição em análise', 'Terms under review', 'Konditionen werden geprüft'],
  ['Qual é sua decisão?', 'What is your decision?', 'Wie möchten Sie entscheiden?'],
  ['O aceite manifesta interesse nesta pré-proposta do laboratório e não substitui a proposta oficial do Nectar. Se algo precisar mudar, recuse e explique o ajuste necessário; a equipe poderá emitir uma nova pré-proposta.', 'Acceptance confirms your interest in this laboratory preliminary proposal and does not replace the official Nectar proposal. If changes are needed, decline it and explain the adjustment; the team can issue a revised proposal.', 'Die Annahme bestätigt Ihr Interesse an diesem Vorangebot des Labors und ersetzt nicht das offizielle Nectar-Angebot. Wenn Änderungen nötig sind, lehnen Sie es ab und erläutern Sie die Anpassung; das Team kann ein überarbeitetes Angebot erstellen.'],
  ['Li e desejo prosseguir com esta pré-proposta.', 'I have read it and want to proceed with this preliminary proposal.', 'Ich habe das Vorangebot gelesen und möchte fortfahren.'],
  ['O que precisa ser alterado?', 'What needs to be changed?', 'Was muss geändert werden?'],
  ['Ex.: prazo, escopo, quantidade ou condição comercial', 'E.g. deadline, scope, quantity or commercial terms', 'Z. B. Termin, Umfang, Menge oder kaufmännische Bedingung'],
  ['Confirmar recusa', 'Confirm decline', 'Ablehnung bestätigen'],
  ['Aceite registrado', 'Acceptance recorded', 'Annahme erfasst'],
  ['A equipe foi informada e poderá enviar uma nova pré-proposta.', 'The team has been notified and can send a revised preliminary proposal.', 'Das Team wurde informiert und kann ein überarbeitetes Vorangebot senden.'],
  ['Documentos privados vinculados somente a este trabalho.', 'Private documents linked only to this work.', 'Private Dokumente, die nur diesem Auftrag zugeordnet sind.'],
  ['Nenhum arquivo foi anexado a esta solicitação.', 'No files were attached to this request.', 'Dieser Anfrage wurden keine Dateien beigefügt.'],
  ['A porcentagem indica o progresso da etapa atual, não do contrato inteiro.', 'The percentage shows progress for the current stage, not for the entire contract.', 'Der Prozentsatz zeigt den Fortschritt der aktuellen Phase, nicht des gesamten Auftrags.'],
  ['A equipe ainda está preparando o acompanhamento', 'The team is still preparing the tracking stages', 'Das Team bereitet die Auftragsverfolgung noch vor'],
  ['As etapas aparecerão aqui depois da triagem inicial da solicitação.', 'The stages will appear here after the initial review of the request.', 'Die Phasen erscheinen hier nach der ersten Prüfung der Anfrage.'],
  ['Concluído', 'Completed', 'Abgeschlossen'],
  ['Em andamento', 'In progress', 'In Bearbeitung'],
  ['A fazer', 'To do', 'Ausstehend'],
  ['concluído', 'complete', 'abgeschlossen'],
  ['Canal vinculado a esta solicitação.', 'Channel linked to this request.', 'Dieser Anfrage zugeordneter Nachrichtenkanal.'],
  ['Nova mensagem', 'New message', 'Neue Nachricht'],
  ['Escreva uma mensagem para a equipe', 'Write a message to the team', 'Nachricht an das Team schreiben'],
  ['Remover', 'Remove', 'Entfernen'],
  ['Usamos seus dados para identificar a empresa, analisar solicitações, acompanhar trabalhos e manter este canal de mensagens. O acesso é restrito a usuários aprovados e à equipe autorizada.', 'We use your data to identify the company, review requests, track work and maintain this messaging channel. Access is restricted to approved users and authorized staff.', 'Wir verwenden Ihre Daten, um das Unternehmen zu identifizieren, Anfragen zu prüfen, Aufträge zu verfolgen und diesen Nachrichtenkanal bereitzustellen. Der Zugriff ist auf genehmigte Benutzer und autorisierte Mitarbeitende beschränkt.'],
  ['Não envie dados pessoais ou industriais que não sejam necessários ao serviço.', 'Do not send personal or industrial data that is not required for the service.', 'Senden Sie keine personenbezogenen oder industriellen Daten, die für die Leistung nicht erforderlich sind.'],
  ['Arquivos e mensagens ficam vinculados à solicitação e protegidos por controle de acesso.', 'Files and messages remain linked to the request and protected by access control.', 'Dateien und Nachrichten bleiben der Anfrage zugeordnet und durch Zugriffskontrollen geschützt.'],
  ['Você pode consultar a política completa e solicitar correção ou atendimento pelo canal informado nela.', 'You can read the full policy and request corrections or support through the channel indicated there.', 'Sie können die vollständige Richtlinie lesen und über den dort genannten Kanal Berichtigung oder Unterstützung anfordern.'],
  ['Li e estou ciente deste aviso de privacidade.', 'I have read and acknowledge this privacy notice.', 'Ich habe diesen Datenschutzhinweis gelesen und zur Kenntnis genommen.'],
  ['Versão', 'Version', 'Version'],
  ['texto de homologação sujeito à validação institucional.', 'validation text subject to institutional approval.', 'Validierungstext vorbehaltlich institutioneller Freigabe.'],
  ['Este trabalho ficará vinculado a', 'This work will be linked to', 'Dieser Auftrag wird zugeordnet zu'],
  ['e aparecerá imediatamente no seu acompanhamento.', 'and will immediately appear in your tracking area.', 'und erscheint sofort in Ihrer Auftragsverfolgung.'],
  ['Fechar nova solicitação', 'Close new request', 'Neue Anfrage schließen'],
  ['Telefone para este trabalho', 'Phone number for this work', 'Telefonnummer für diesen Auftrag'],
  ['(opcional)', '(optional)', '(optional)'],
  ['Prazo em dias', 'Term in days', 'Frist in Tagen'],
  ['Ex.: modelo STEP, relatório dimensional ou investigação de falha', 'E.g. STEP model, dimensional report or failure investigation', 'Z. B. STEP-Modell, Maßbericht oder Fehleruntersuchung'],
  ['Inclua dimensões, tolerâncias, finalidade, pontos críticos e o entregável esperado.', 'Include dimensions, tolerances, purpose, critical points and the expected deliverable.', 'Geben Sie Abmessungen, Toleranzen, Zweck, kritische Punkte und das erwartete Ergebnis an.'],
  ['Envie no máximo cinco arquivos por solicitação, incluindo os que já foram enviados.', 'Send no more than five files per request, including files already uploaded.', 'Senden Sie höchstens fünf Dateien pro Anfrage, einschließlich bereits hochgeladener Dateien.'],
  ['Informe um telefone válido, sem letras ou símbolos inválidos.', 'Enter a valid phone number without letters or invalid symbols.', 'Geben Sie eine gültige Telefonnummer ohne Buchstaben oder ungültige Zeichen ein.'],
  ['A conexão protegida está indisponível. Atualize a página e tente novamente.', 'The secure connection is unavailable. Refresh the page and try again.', 'Die sichere Verbindung ist nicht verfügbar. Aktualisieren Sie die Seite und versuchen Sie es erneut.'],
  ['Não foi possível registrar o novo trabalho.', 'The new work request could not be submitted.', 'Der neue Auftrag konnte nicht erfasst werden.'],
  ['Envie no máximo cinco arquivos.', 'Send no more than five files.', 'Senden Sie höchstens fünf Dateien.'],
  ['Formato não permitido:', 'File format not allowed:', 'Dateiformat nicht zulässig:'],
  ['O arquivo', 'The file', 'Die Datei'],
  ['excede o limite permitido.', 'exceeds the allowed size.', 'überschreitet die zulässige Größe.'],
  ['Informe um CNPJ válido. A validação verifica apenas o formato e os dígitos verificadores.', 'Enter a valid Brazilian company registration number. Validation checks its format and check digits.', 'Geben Sie eine gültige brasilianische Unternehmensnummer ein. Geprüft werden Format und Prüfziffern.'],
  ['A persistência da homologação está temporariamente indisponível.', 'The validation environment is temporarily unavailable.', 'Die Validierungsumgebung ist vorübergehend nicht verfügbar.'],
  ['Informe um telefone válido, usando somente números, espaços, parênteses, hífen e + no início.', 'Enter a valid phone number using only numbers, spaces, parentheses, hyphens and an optional leading +.', 'Geben Sie eine gültige Telefonnummer ein. Zulässig sind Zahlen, Leerzeichen, Klammern, Bindestriche und optional ein führendes +.'],
  ['Não foi possível registrar a solicitação demonstrativa.', 'The request could not be submitted.', 'Die Anfrage konnte nicht erfasst werden.'],
  ['A homologação não retornou o protocolo esperado.', 'The validation environment did not return the expected tracking number.', 'Die Validierungsumgebung hat nicht die erwartete Vorgangsnummer zurückgegeben.'],
  ['Protocolo', 'Tracking number', 'Vorgangsnummer'],
  ['vinculado ao e-mail', 'linked to the email address', 'verknüpft mit der E-Mail-Adresse'],
  ['Informe os 14 números do CNPJ no formato 00.000.000/0000-00.', 'Enter all 14 digits in the format 00.000.000/0000-00.', 'Geben Sie alle 14 Ziffern im Format 00.000.000/0000-00 ein.'],
  ['Informe o material', 'Enter the material', 'Material angeben'],
  ['Endereço copiado. Cole-o no aplicativo de e-mail que preferir.', 'Address copied. Paste it into your preferred email app.', 'Adresse kopiert. Fügen Sie sie in Ihre bevorzugte E-Mail-App ein.'],
  ['Contato por e-mail', 'Email contact', 'Kontakt per E-Mail'],
  ['Use o acesso abaixo com o mesmo e-mail. Se o Cliente já estiver cadastrado, este novo trabalho será acrescentado à empresa existente; caso seja o primeiro, a área protegida será ativada. Os arquivos selecionados permaneceram neste dispositivo e poderão ser enviados na etapa autenticada.', 'Use the access link below with the same email address. If the customer is already registered, this work will be added to the existing company; otherwise, the protected area will be activated. Selected files remain on this device and can be uploaded after authentication.', 'Verwenden Sie den Zugang unten mit derselben E-Mail-Adresse. Ist der Kunde bereits registriert, wird dieser Auftrag dem bestehenden Unternehmen hinzugefügt; andernfalls wird der geschützte Bereich aktiviert. Ausgewählte Dateien bleiben auf diesem Gerät und können nach der Anmeldung hochgeladen werden.'],
  ['DEMONSTRAÇÃO', 'DEMONSTRATION', 'DEMONSTRATION'],
  ['ÁREA DO CLIENTE', 'CUSTOMER AREA', 'KUNDENBEREICH'],
  ['CENTRAL DO CLIENTE', 'CUSTOMER CENTER', 'KUNDENZENTRALE'],
  ['Todos os trabalhos da sua empresa em um só lugar.', 'All your company’s work in one place.', 'Alle Aufträge Ihres Unternehmens an einem Ort.'],
  ['Abra novas solicitações, acompanhe vários trabalhos ao mesmo tempo e alterne livremente entre pré-propostas, etapas e mensagens sem repetir cadastro ou ativação.', 'Create new requests, track multiple jobs at the same time and switch freely between preliminary proposals, stages and messages without registering or activating again.', 'Erstellen Sie neue Anfragen, verfolgen Sie mehrere Aufträge gleichzeitig und wechseln Sie frei zwischen Vorangeboten, Phasen und Nachrichten, ohne sich erneut zu registrieren oder zu aktivieren.'],
  ['Acesso restrito à sua empresa', 'Access restricted to your company', 'Zugriff auf Ihr Unternehmen beschränkt'],
  ['Dados de homologação permanecem demonstrativos.', 'Validation data remains demonstrative.', 'Validierungsdaten bleiben Demonstrationsdaten.'],
  ['Perfil', 'Profile', 'Profil'],
  ['Nome de exibição', 'Display name', 'Anzeigename'],
  ['E-mail de acesso', 'Sign-in email', 'E-Mail für die Anmeldung'],
  ['Cargo ou função na empresa', 'Job title or role at the company', 'Position oder Funktion im Unternehmen'],
  ['Salvar', 'Save', 'Speichern'],
  ['Mensagens não lidas', 'Unread messages', 'Ungelesene Nachrichten'],
  ['Pesquisar por protocolo, serviço, estado ou data', 'Search by tracking number, service, status or date', 'Nach Vorgangsnummer, Leistung, Status oder Datum suchen'],
  ['Mais novos primeiro', 'Newest first', 'Neueste zuerst'],
  ['Mais antigos primeiro', 'Oldest first', 'Älteste zuerst'],
  ['Maior valor', 'Highest value', 'Höchster Wert'],
  ['Tipo de serviço', 'Service type', 'Leistungsart'],
  ['Situação', 'Status', 'Status'],
  ['Aguardando minha decisão', 'Awaiting my decision', 'Wartet auf meine Entscheidung'],
  ['Serviços ativos', 'Active services', 'Aktive Leistungen'],
  ['Serviços concluídos', 'Completed services', 'Abgeschlossene Leistungen'],
  ['Revisão solicitada', 'Revision requested', 'Überarbeitung angefordert'],
  ['Ainda sem pré-proposta', 'No preliminary proposal yet', 'Noch kein Vorangebot'],
  ['Comece seu primeiro trabalho', 'Start your first work request', 'Starten Sie Ihren ersten Auftrag'],
  ['Registrar solicitação', 'Submit request', 'Anfrage erfassen'],
  ['Seus trabalhos', 'Your work', 'Ihre Aufträge'],
  ['Selecione o que deseja acompanhar', 'Select what you want to track', 'Wählen Sie den Auftrag aus, den Sie verfolgen möchten'],
  ['Recebida em', 'Received on', 'Eingegangen am'],
  ['Atualizar', 'Refresh', 'Aktualisieren'],
  ['Pré-proposta comercial', 'Commercial preliminary proposal', 'Kaufmännisches Vorangebot'],
  ['Baixando…', 'Downloading…', 'Wird heruntergeladen…'],
  ['Baixar PDF emitido', 'Download issued PDF', 'Ausgestelltes PDF herunterladen'],
  ['Registrando…', 'Recording…', 'Wird erfasst…'],
  ['Registrada em', 'Recorded on', 'Erfasst am'],
  ['enviado em', 'sent on', 'gesendet am'],
  ['Atualizado em', 'Updated on', 'Aktualisiert am'],
  ['Ler política completa', 'Read full policy', 'Vollständige Richtlinie lesen'],
  ['NOVO TRABALHO', 'NEW WORK REQUEST', 'NEUER AUFTRAG'],
  ['Registrar outra solicitação', 'Submit another request', 'Weitere Anfrage erfassen'],
  ['Seu perfil e sua empresa já foram confirmados. Não é necessário informar CNPJ nem ativar outra conta.', 'Your profile and company have already been confirmed. You do not need to enter a company registration number or activate another account.', 'Ihr Profil und Ihr Unternehmen wurden bereits bestätigt. Sie müssen keine Unternehmensnummer eingeben oder ein weiteres Konto aktivieren.'],
  ['Adicionar imagens ou outros arquivos', 'Add images or other files', 'Bilder oder andere Dateien hinzufügen'],
  ['Até 5 arquivos. PDF e imagens: 10 MB cada. CAD: 50 MB cada.', 'Up to 5 files. PDFs and images: 10 MB each. CAD: 50 MB each.', 'Bis zu 5 Dateien. PDF und Bilder: jeweils 10 MB. CAD: jeweils 50 MB.'],
  ['Concluir sem os arquivos restantes', 'Finish without the remaining files', 'Ohne die restlichen Dateien abschließen'],
  ['Enviando…', 'Sending…', 'Wird gesendet…'],
  ['Tentar enviar arquivos', 'Retry file upload', 'Dateien erneut hochladen'],
  ['Centro de Excelência em Metrologia — início', 'Metrology Center of Excellence — home', 'Kompetenzzentrum für Messtechnik — Startseite'],
  ['Centro de Excelência em Metrologia SENAI ZEISS — início', 'SENAI ZEISS Metrology Center of Excellence — home', 'SENAI ZEISS Kompetenzzentrum für Messtechnik — Startseite'],
  ['Solicitação de análise metrológica', 'Metrology analysis request', 'Anfrage zur messtechnischen Analyse'],
  ['Gestor da empresa', 'Company manager', 'Unternehmensleitung'],
  ['Contato da empresa', 'Company contact', 'Ansprechperson des Unternehmens'],
  ['Não foi possível carregar seu acompanhamento. Tente novamente.', 'Your tracking information could not be loaded. Try again.', 'Ihre Auftragsverfolgung konnte nicht geladen werden. Versuchen Sie es erneut.'],
  ['registrada e vinculada à sua empresa. Você já pode alternar entre os trabalhos.', 'was submitted and linked to your company. You can now switch between work items.', 'wurde erfasst und Ihrem Unternehmen zugeordnet. Sie können jetzt zwischen den Aufträgen wechseln.'],
  ['Na demonstração local, o arquivo é apenas representativo. Use a homologação autenticada para testar o download privado.', 'In the local demonstration, the file is illustrative only. Use the authenticated validation environment to test the private download.', 'In der lokalen Demonstration ist die Datei nur beispielhaft. Verwenden Sie die authentifizierte Validierungsumgebung, um den privaten Download zu testen.'],
  ['Não foi possível baixar este anexo protegido.', 'This protected attachment could not be downloaded.', 'Dieser geschützte Anhang konnte nicht heruntergeladen werden.'],
  ['Não foi possível registrar a ciência do aviso de privacidade.', 'Your acknowledgement of the privacy notice could not be recorded.', 'Ihre Bestätigung des Datenschutzhinweises konnte nicht erfasst werden.'],
  ['Não foi possível enviar a mensagem.', 'The message could not be sent.', 'Die Nachricht konnte nicht gesendet werden.'],
  ['A mensagem foi enviada, mas', 'The message was sent, but', 'Die Nachricht wurde gesendet, aber'],
  ['não pôde ser anexado.', 'could not be attached.', 'konnte nicht angehängt werden.'],
  ['não pôde ser registrado.', 'could not be recorded.', 'konnte nicht erfasst werden.'],
  ['Use a área autenticada para baixar anexos de mensagens.', 'Use the authenticated area to download message attachments.', 'Verwenden Sie den authentifizierten Bereich, um Nachrichtenanhänge herunterzuladen.'],
  ['Não foi possível baixar o anexo protegido.', 'The protected attachment could not be downloaded.', 'Der geschützte Anhang konnte nicht heruntergeladen werden.'],
  ['Informe um nome entre 2 e 120 caracteres.', 'Enter a name between 2 and 120 characters.', 'Geben Sie einen Namen mit 2 bis 120 Zeichen ein.'],
  ['Informe um endereço de e-mail válido.', 'Enter a valid email address.', 'Geben Sie eine gültige E-Mail-Adresse ein.'],
  ['Informe um cargo ou função entre 2 e 120 caracteres.', 'Enter a job title or role between 2 and 120 characters.', 'Geben Sie eine Position oder Funktion mit 2 bis 120 Zeichen ein.'],
  ['Não foi possível atualizar nome e cargo do perfil.', 'The profile name and job title could not be updated.', 'Name und Position des Profils konnten nicht aktualisiert werden.'],
  ['Nome e cargo foram salvos, mas não foi possível alterar o e-mail.', 'Name and job title were saved, but the email address could not be changed.', 'Name und Position wurden gespeichert, die E-Mail-Adresse konnte jedoch nicht geändert werden.'],
  ['Nome, cargo e e-mail de acesso atualizados.', 'Name, job title and sign-in email updated.', 'Name, Position und Anmelde-E-Mail wurden aktualisiert.'],
  ['Nome e cargo do perfil atualizados. A empresa e as permissões permanecem protegidas.', 'Profile name and job title updated. Company and permissions remain protected.', 'Profilname und Position wurden aktualisiert. Unternehmen und Berechtigungen bleiben geschützt.'],
  ['Na demonstração local, o PDF não é persistido. Use a homologação autenticada para testar o download protegido.', 'In the local demonstration, the PDF is not stored. Use the authenticated validation environment to test the protected download.', 'In der lokalen Demonstration wird das PDF nicht gespeichert. Verwenden Sie die authentifizierte Validierungsumgebung, um den geschützten Download zu testen.'],
  ['O PDF emitido ainda não está disponível para download.', 'The issued PDF is not yet available for download.', 'Das ausgestellte PDF steht noch nicht zum Download bereit.'],
  ['Não foi possível baixar o PDF protegido.', 'The protected PDF could not be downloaded.', 'Das geschützte PDF konnte nicht heruntergeladen werden.'],
  ['A verificação de integridade do PDF falhou. O download foi bloqueado; avise a equipe do laboratório.', 'PDF integrity verification failed. The download was blocked; notify the laboratory team.', 'Die Integritätsprüfung des PDFs ist fehlgeschlagen. Der Download wurde blockiert; informieren Sie das Laborteam.'],
  ['PDF verificado:', 'PDF verified:', 'PDF geprüft:'],
  ['Esta pré-proposta não pode mais ser aceita. Atualize a página ou fale com a equipe.', 'This preliminary proposal can no longer be accepted. Refresh the page or contact the team.', 'Dieses Vorangebot kann nicht mehr angenommen werden. Aktualisieren Sie die Seite oder wenden Sie sich an das Team.'],
  ['Não foi possível registrar o aceite da pré-proposta. Tente novamente.', 'Acceptance of the preliminary proposal could not be recorded. Try again.', 'Die Annahme des Vorangebots konnte nicht erfasst werden. Versuchen Sie es erneut.'],
  ['Aceite registrado. O trabalho começará somente após a liberação do Administrador.', 'Acceptance recorded. Work will begin only after release by the Administrator.', 'Annahme erfasst. Der Auftrag beginnt erst nach Freigabe durch den Administrator.'],
  ['Esta pré-proposta não pode mais ser recusada. Atualize a página e confira o estado atual.', 'This preliminary proposal can no longer be declined. Refresh the page and check its current status.', 'Dieses Vorangebot kann nicht mehr abgelehnt werden. Aktualisieren Sie die Seite und prüfen Sie den aktuellen Status.'],
  ['Não foi possível registrar a recusa. Tente novamente.', 'The decline could not be recorded. Try again.', 'Die Ablehnung konnte nicht erfasst werden. Versuchen Sie es erneut.'],
  ['Recusa registrada. A equipe poderá preparar e emitir uma nova pré-proposta para este trabalho.', 'Decline recorded. The team can prepare and issue a revised preliminary proposal for this work.', 'Ablehnung erfasst. Das Team kann ein überarbeitetes Vorangebot für diesen Auftrag erstellen und ausstellen.'],
  ['já foi criada, mas', 'was created, but', 'wurde erstellt, aber'],
  ['arquivo(s) não foram enviados. Tente novamente ou conclua sem eles.', 'file(s) could not be uploaded. Try again or finish without them.', 'Datei(en) konnten nicht hochgeladen werden. Versuchen Sie es erneut oder schließen Sie ohne sie ab.'],
  ['O formato de', 'The format of', 'Das Format von'],
  ['não é aceito. Use PDF, imagem ou arquivo CAD.', 'is not accepted. Use a PDF, image or CAD file.', 'wird nicht akzeptiert. Verwenden Sie PDF-, Bild- oder CAD-Dateien.'],
  ['excede o limite de', 'exceeds the limit of', 'überschreitet das Limit von'],
  ['formato não permitido.', 'file format not allowed.', 'Dateiformat nicht zulässig.'],
  ['o limite por arquivo é 10 MB.', 'the per-file limit is 10 MB.', 'die Höchstgröße pro Datei beträgt 10 MB.'],
  ['Envie no máximo cinco arquivos por mensagem.', 'Send no more than five files per message.', 'Senden Sie höchstens fünf Dateien pro Nachricht.'],
  ['Envie no máximo cinco arquivos por solicitação.', 'Send no more than five files per request.', 'Senden Sie höchstens fünf Dateien pro Anfrage.'],
  ['Serviço concluído', 'Service completed', 'Leistung abgeschlossen'],
  ['O trabalho foi concluído e o encerramento foi aprovado pela equipe do laboratório.', 'The work was completed and its closure was approved by the laboratory team.', 'Der Auftrag wurde abgeschlossen und der Abschluss vom Laborteam freigegeben.'],
  ['Serviço cancelado', 'Service cancelled', 'Leistung storniert'],
  ['Este trabalho foi cancelado. Fale com a equipe pelo canal de mensagens para mais informações.', 'This work was cancelled. Contact the team through the messaging channel for more information.', 'Dieser Auftrag wurde storniert. Weitere Informationen erhalten Sie über den Nachrichtenkanal vom Team.'],
  ['Início confirmado', 'Start confirmed', 'Start bestätigt'],
  ['O laboratório liberou o trabalho e está preparando as etapas de acompanhamento.', 'The laboratory released the work and is preparing its tracking stages.', 'Das Labor hat den Auftrag freigegeben und bereitet die Phasen der Auftragsverfolgung vor.'],
  ['Planejamento iniciado', 'Planning started', 'Planung begonnen'],
  ['O trabalho foi liberado e aguarda o início da primeira etapa.', 'The work was released and is awaiting the start of its first stage.', 'Der Auftrag wurde freigegeben und wartet auf den Beginn der ersten Phase.'],
  ['Aguardando o Administrador confirmar a liberação do trabalho.', 'Waiting for the Administrator to confirm release of the work.', 'Warten auf die Freigabebestätigung durch den Administrator.'],
  ['Analise a pré-proposta emitida e informe se deseja prosseguir.', 'Review the issued preliminary proposal and indicate whether you wish to proceed.', 'Prüfen Sie das ausgestellte Vorangebot und teilen Sie mit, ob Sie fortfahren möchten.'],
  ['A equipe recebeu sua decisão e poderá preparar uma nova pré-proposta para este trabalho.', 'The team received your decision and can prepare a revised preliminary proposal for this work.', 'Das Team hat Ihre Entscheidung erhalten und kann ein überarbeitetes Vorangebot für diesen Auftrag erstellen.'],
  ['Aguardando triagem', 'Awaiting initial review', 'Wartet auf Erstprüfung'],
  ['A equipe ainda não cadastrou as etapas deste trabalho.', 'The team has not yet created the stages for this work.', 'Das Team hat die Phasen für diesen Auftrag noch nicht angelegt.'],
  ['Etapa em andamento:', 'Stage in progress:', 'Phase in Bearbeitung:'],
  ['concluída.', 'complete.', 'abgeschlossen.'],
  ['Etapas concluídas', 'Stages completed', 'Phasen abgeschlossen'],
  ['A equipe concluiu as etapas visíveis e está preparando o encerramento do trabalho.', 'The team completed the visible stages and is preparing closure of the work.', 'Das Team hat die sichtbaren Phasen abgeschlossen und bereitet den Auftragsabschluss vor.'],
  ['Trabalho liberado', 'Work released', 'Auftrag freigegeben'],
  ['O laboratório confirmou o início; a primeira etapa ainda será iniciada pela equipe.', 'The laboratory confirmed the start; the team has not yet begun the first stage.', 'Das Labor hat den Start bestätigt; die erste Phase wird noch vom Team begonnen.'],
  ['Aguardando início', 'Awaiting start', 'Wartet auf Start'],
  ['As etapas foram planejadas, mas a execução ainda não começou.', 'The stages have been planned, but execution has not started yet.', 'Die Phasen wurden geplant, die Ausführung hat jedoch noch nicht begonnen.'],
  ['Registrado em', 'Recorded on', 'Erfasst am'],
  ['O trabalho foi concluído e encerrado pela equipe.', 'The work was completed and closed by the team.', 'Der Auftrag wurde vom Team fertiggestellt und abgeschlossen.'],
  ['O laboratório confirmou a liberação e o trabalho está em execução.', 'The laboratory confirmed release and the work is in progress.', 'Das Labor hat die Freigabe bestätigt und der Auftrag wird ausgeführt.'],
  ['O trabalho foi cancelado; consulte a equipe pelo canal de mensagens.', 'The work was cancelled; contact the team through the messaging channel.', 'Der Auftrag wurde storniert; wenden Sie sich über den Nachrichtenkanal an das Team.'],
  ['Agora o laboratório precisa confirmar a liberação do trabalho.', 'The laboratory must now confirm release of the work.', 'Das Labor muss nun die Freigabe des Auftrags bestätigen.'],
  ['E-mail ou senha inválidos. Verifique os dados ou recupere sua senha.', 'Invalid email or password. Check your details or reset your password.', 'E-Mail-Adresse oder Passwort ungültig. Prüfen Sie Ihre Daten oder setzen Sie Ihr Passwort zurück.'],
  ['Não foi possível iniciar a recuperação agora. Aguarde alguns instantes e tente novamente.', 'Password recovery could not be started now. Wait a moment and try again.', 'Die Passwortwiederherstellung konnte nicht gestartet werden. Warten Sie einen Moment und versuchen Sie es erneut.'],
  ['Se o e-mail estiver cadastrado, você receberá um link seguro para criar uma nova senha.', 'If the email address is registered, you will receive a secure link to create a new password.', 'Wenn die E-Mail-Adresse registriert ist, erhalten Sie einen sicheren Link zum Erstellen eines neuen Passworts.'],
  ['A nova senha deve ter pelo menos 10 caracteres.', 'The new password must contain at least 10 characters.', 'Das neue Passwort muss mindestens 10 Zeichen lang sein.'],
  ['A confirmação não corresponde à nova senha.', 'The confirmation does not match the new password.', 'Die Bestätigung stimmt nicht mit dem neuen Passwort überein.'],
  ['O link ainda não foi validado ou já expirou. Abra novamente o link mais recente recebido por e-mail.', 'The link has not been validated yet or has expired. Open the most recent link received by email again.', 'Der Link wurde noch nicht bestätigt oder ist abgelaufen. Öffnen Sie erneut den zuletzt per E-Mail erhaltenen Link.'],
  ['O link expirou ou a senha não pôde ser alterada. Solicite uma nova recuperação.', 'The link expired or the password could not be changed. Request a new recovery email.', 'Der Link ist abgelaufen oder das Passwort konnte nicht geändert werden. Fordern Sie eine neue Wiederherstellung an.'],
  ['Senha alterada. Você já pode continuar com a sessão protegida.', 'Password changed. You can now continue with the protected session.', 'Passwort geändert. Sie können die geschützte Sitzung jetzt fortsetzen.'],
  ['Voltar à página pública', 'Back to the public website', 'Zur öffentlichen Website'],
  ['Acesso protegido', 'Protected access', 'Geschützter Zugang'],
  ['Validando acesso', 'Validating access', 'Zugang wird geprüft'],
  ['Aguarde enquanto confirmamos sua sessão e o tipo de acesso.', 'Please wait while we confirm your session and access type.', 'Bitte warten Sie, während wir Ihre Sitzung und Zugriffsart prüfen.'],
  ['Integração de homologação pendente', 'Validation integration pending', 'Validierungsintegration ausstehend'],
  ['O acesso permanece fechado até a URL e a chave pública do Supabase de homologação serem configuradas.', 'Access remains closed until the validation Supabase URL and public key are configured.', 'Der Zugang bleibt geschlossen, bis URL und öffentlicher Schlüssel der Supabase-Validierungsumgebung konfiguriert sind.'],
  ['Acesso ainda não vinculado', 'Access not linked yet', 'Zugang noch nicht zugeordnet'],
  ['Sua identidade foi confirmada, mas não há perfil interno nem vínculo aprovado com uma empresa. Clientes recebem esse vínculo por convite da equipe após a análise da solicitação.', 'Your identity was confirmed, but there is no internal profile or approved company link. Customers receive this link through a team invitation after their request is reviewed.', 'Ihre Identität wurde bestätigt, aber es gibt noch kein internes Profil oder eine genehmigte Unternehmenszuordnung. Kunden erhalten diese Zuordnung nach Prüfung ihrer Anfrage über eine Einladung des Teams.'],
  ['Não foi possível validar o acesso', 'Access could not be validated', 'Zugang konnte nicht geprüft werden'],
  ['A autenticação está temporariamente indisponível.', 'Authentication is temporarily unavailable.', 'Die Authentifizierung ist vorübergehend nicht verfügbar.'],
  ['Tentar novamente', 'Try again', 'Erneut versuchen'],
  ['Ative sua conta', 'Activate your account', 'Konto aktivieren'],
  ['Crie uma nova senha', 'Create a new password', 'Neues Passwort erstellen'],
  ['Use uma senha exclusiva com pelo menos 10 caracteres.', 'Use a unique password containing at least 10 characters.', 'Verwenden Sie ein eindeutiges Passwort mit mindestens 10 Zeichen.'],
  ['Validando o link seguro recebido por e-mail…', 'Validating the secure link received by email…', 'Der per E-Mail erhaltene sichere Link wird geprüft…'],
  ['Nova senha', 'New password', 'Neues Passwort'],
  ['Confirmar nova senha', 'Confirm new password', 'Neues Passwort bestätigen'],
  ['Alterando…', 'Changing…', 'Wird geändert…'],
  ['Salvar nova senha', 'Save new password', 'Neues Passwort speichern'],
  ['Recuperar senha', 'Reset password', 'Passwort zurücksetzen'],
  ['Informe o e-mail usado no portal. Por segurança, a confirmação não revela se o endereço está cadastrado.', 'Enter the email address used in the portal. For security, the confirmation does not reveal whether the address is registered.', 'Geben Sie die im Portal verwendete E-Mail-Adresse ein. Aus Sicherheitsgründen wird nicht offengelegt, ob die Adresse registriert ist.'],
  ['Enviar link seguro', 'Send secure link', 'Sicheren Link senden'],
  ['Voltar ao login', 'Back to sign in', 'Zurück zur Anmeldung'],
  ['Entrar no Portal de Metrologia', 'Sign in to the Metrology Portal', 'Beim Messtechnik-Portal anmelden'],
  ['Equipe interna e clientes convidados usam o mesmo acesso. Não é preciso entrar para enviar uma solicitação.', 'Staff and invited customers use the same sign-in. You do not need to sign in to submit a request.', 'Mitarbeitende und eingeladene Kunden verwenden dieselbe Anmeldung. Zum Senden einer Anfrage ist keine Anmeldung erforderlich.'],
  ['Senha', 'Password', 'Passwort'],
  ['Validando…', 'Validating…', 'Wird geprüft…'],
  ['Esqueci minha senha', 'Forgot my password', 'Passwort vergessen'],
  ['Fazer solicitação sem login', 'Submit request without signing in', 'Anfrage ohne Anmeldung senden'],
] as const satisfies readonly TrioTraducao[];
