import type { TrioTraducao } from './traducoes-complementares';

export const traducoesEquipamentos = [
  ['Medição tridimensional tátil', 'Tactile coordinate measurement', 'Taktile Koordinatenmesstechnik'],
  ['CMM compacta e robusta para inspeções dimensionais próximas ao ambiente produtivo.', 'Compact, robust CMM for dimensional inspection close to the production environment.', 'Kompaktes, robustes KMG für Maßprüfungen nahe der Fertigung.'],
  ['A configuração instalada no Centro é a DuraMax HTG 5/5/5, uma máquina de medição por coordenadas compacta com construção aberta e acesso direto à mesa.', 'The Center operates a DuraMax HTG 5/5/5, a compact coordinate measuring machine with an open design and direct table access.', 'Im Zentrum ist eine DuraMax HTG 5/5/5 installiert, ein kompaktes Koordinatenmessgerät mit offener Bauweise und direktem Zugang zum Messtisch.'],
  ['O sensor ZEISS VAST XXT permite medições rápidas de ponto único e digitalização tátil de contornos e superfícies livres. A mesa rotativa amplia o fluxo para medições em quatro eixos.', 'The ZEISS VAST XXT sensor enables fast single-point measurements and tactile scanning of contours and freeform surfaces. The rotary table extends the workflow to four-axis measurements.', 'Der ZEISS VAST XXT Sensor ermöglicht schnelle Einzelpunktmessungen und taktiles Scannen von Konturen und Freiformflächen. Der Drehtisch erweitert den Ablauf auf Vier-Achs-Messungen.'],
  ['Inspeção de peças usinadas', 'Inspection of machined parts', 'Prüfung bearbeiteter Bauteile'],
  ['Controle de recebimento e processo', 'Incoming and process inspection', 'Wareneingangs- und Prozessprüfung'],
  ['Validação de dispositivos e ferramentais', 'Validation of fixtures and tooling', 'Validierung von Vorrichtungen und Werkzeugen'],
  ['Medição de geometrias e elementos dimensionais', 'Measurement of geometries and dimensional features', 'Messung von Geometrien und Maßmerkmalen'],
  ['Volume de medição instalado: 500 × 500 × 500 mm', 'Installed measuring volume: 500 × 500 × 500 mm', 'Installiertes Messvolumen: 500 × 500 × 500 mm'],
  ['Sensor ZEISS VAST XXT para ponto único e digitalização de contornos', 'ZEISS VAST XXT sensor for single-point measurement and contour scanning', 'ZEISS VAST XXT Sensor für Einzelpunktmessung und Konturscanning'],
  ['Medição em quatro eixos com mesa rotativa', 'Four-axis measurement with rotary table', 'Vier-Achs-Messung mit Drehtisch'],
  ['Escala Zerodur e sensores para correção da temperatura da peça', 'Zerodur scale and sensors for workpiece temperature compensation', 'Zerodur-Maßstab und Sensoren zur Werkstücktemperaturkompensation'],
  ['Dimensões lineares e angulares', 'Linear and angular dimensions', 'Lineare Maße und Winkel'],
  ['Forma e posição', 'Form and position', 'Form und Lage'],
  ['Perfis e contornos', 'Profiles and contours', 'Profile und Konturen'],
  ['Comparação com modelo CAD', 'Comparison with CAD model', 'Vergleich mit CAD-Modell'],
  ['Construção aberta correspondente ao modelo real do Centro', 'Open design matching the actual model installed at the Center', 'Offene Bauweise entsprechend dem tatsächlich im Zentrum installierten Modell'],
  ['Baixa expansão térmica da escala Zerodur', 'Low thermal expansion of the Zerodur scale', 'Geringe Wärmeausdehnung des Zerodur-Maßstabs'],
  ['Correção de temperatura da peça de trabalho', 'Workpiece temperature compensation', 'Werkstücktemperaturkompensation'],
  ['Fluxos programáveis e relatórios rastreáveis', 'Programmable workflows and traceable reports', 'Programmierbare Abläufe und rückverfolgbare Berichte'],
  ['Configuração identificada no Centro: DuraMax HTG 5/5/5, volume 500 × 500 × 500 mm, sensor VAST XXT e mesa rotativa. A incerteza aplicável e as condições da medição são confirmadas na análise técnica.', 'Configuration identified at the Center: DuraMax HTG 5/5/5, 500 × 500 × 500 mm volume, VAST XXT sensor and rotary table. Applicable uncertainty and measurement conditions are confirmed during the technical review.', 'Im Zentrum identifizierte Konfiguration: DuraMax HTG 5/5/5, Volumen 500 × 500 × 500 mm, VAST XXT Sensor und Drehtisch. Die anwendbare Messunsicherheit und die Messbedingungen werden in der technischen Prüfung bestätigt.'],

  ['Medição óptica e multissensor', 'Optical and multisensor measurement', 'Optische und Multisensor-Messtechnik'],
  ['Sistema multissensor para medições ópticas e táteis de peças com geometrias delicadas ou de difícil acesso.', 'Multisensor system for optical and tactile measurement of parts with delicate or hard-to-reach geometries.', 'Multisensorsystem für optische und taktile Messungen an Bauteilen mit empfindlichen oder schwer zugänglichen Geometrien.'],
  ['A configuração O-INSPECT 5/4/3 instalada no Centro reúne medição óptica e por contato em um único sistema, em conformidade declarada no cartaz técnico com a ISO 10360.', 'The O-INSPECT 5/4/3 installed at the Center combines optical and contact measurement in one system; the local technical notice declares compliance with ISO 10360.', 'Die im Zentrum installierte O-INSPECT 5/4/3 vereint optische und taktile Messung in einem System; laut lokalem technischen Aushang entspricht sie ISO 10360.'],
  ['O volume de medição de 500 × 400 × 300 mm atende peças com características delicadas, contornos e elementos que exigem combinar estratégias sem contato e táteis.', 'The 500 × 400 × 300 mm measuring volume accommodates parts with delicate features, contours and elements that require combined non-contact and tactile strategies.', 'Das Messvolumen von 500 × 400 × 300 mm eignet sich für Bauteile mit empfindlichen Merkmalen, Konturen und Elementen, die berührungslose und taktile Strategien kombinieren.'],
  ['Peças plásticas, estampadas e eletrônicas', 'Plastic, stamped and electronic parts', 'Kunststoff-, Stanz- und Elektronikbauteile'],
  ['Componentes com detalhes pequenos', 'Components with small details', 'Komponenten mit kleinen Details'],
  ['Controle de contornos e bordas', 'Contour and edge inspection', 'Kontur- und Kantenprüfung'],
  ['Inspeção de peças sensíveis ao contato', 'Inspection of contact-sensitive parts', 'Prüfung berührungsempfindlicher Bauteile'],
  ['Volume de medição instalado: 500 × 400 × 300 mm', 'Installed measuring volume: 500 × 400 × 300 mm', 'Installiertes Messvolumen: 500 × 400 × 300 mm'],
  ['Medição óptica e por contato no mesmo sistema', 'Optical and contact measurement in the same system', 'Optische und taktile Messung im selben System'],
  ['MPE(E) longitudinal informado em 1D: 1,4 µm + L/250', 'Specified longitudinal MPE(E) in 1D: 1.4 µm + L/250', 'Angegebene longitudinale MPE(E) in 1D: 1,4 µm + L/250'],
  ['MPE(E) longitudinal informado em 2D: 1,6 µm + L/250; em 3D: 1,9 µm + L/250', 'Specified longitudinal MPE(E) in 2D: 1.6 µm + L/250; in 3D: 1.9 µm + L/250', 'Angegebene longitudinale MPE(E) in 2D: 1,6 µm + L/250; in 3D: 1,9 µm + L/250'],
  ['Contornos e arestas', 'Contours and edges', 'Konturen und Kanten'],
  ['Dimensões 2D e 3D', '2D and 3D dimensions', '2D- und 3D-Maße'],
  ['Medição de altura e superfícies', 'Height and surface measurement', 'Höhen- und Oberflächenmessung'],
  ['Flexibilidade multissensor', 'Multisensor flexibility', 'Multisensor-Flexibilität'],
  ['Troca de estratégia sem reposicionar a peça', 'Strategy changes without repositioning the part', 'Strategiewechsel ohne Neupositionierung des Bauteils'],
  ['Apoio a medições sem contato', 'Support for non-contact measurements', 'Unterstützung berührungsloser Messungen'],
  ['Programação e avaliação no ecossistema ZEISS', 'Programming and evaluation in the ZEISS ecosystem', 'Programmierung und Auswertung im ZEISS-Ökosystem'],
  ['Configuração identificada no Centro: O-INSPECT 5/4/3, volume 500 × 400 × 300 mm. As expressões de MPE(E) reproduzem o cartaz local e devem ser interpretadas conforme a ISO 10360 e as condições válidas para a medição.', 'Configuration identified at the Center: O-INSPECT 5/4/3, 500 × 400 × 300 mm volume. The MPE(E) expressions reproduce the local notice and must be interpreted according to ISO 10360 and the valid measurement conditions.', 'Im Zentrum identifizierte Konfiguration: O-INSPECT 5/4/3, Volumen 500 × 400 × 300 mm. Die MPE(E)-Angaben entsprechen dem lokalen Aushang und sind gemäß ISO 10360 sowie den gültigen Messbedingungen auszulegen.'],

  ['Medição tridimensional de alta precisão', 'High-precision coordinate measurement', 'Hochpräzise Koordinatenmesstechnik'],
  ['CMM de alta precisão para geometrias complexas, scanning e inspeções dimensionais exigentes.', 'High-precision CMM for complex geometries, scanning and demanding dimensional inspections.', 'Hochpräzises KMG für komplexe Geometrien, Scanning und anspruchsvolle Maßprüfungen.'],
  ['A configuração instalada é a PRISMO VAST 09/24/07, voltada a medições de alta precisão em peças grandes e geometrias complexas.', 'The installed configuration is the PRISMO VAST 09/24/07, intended for high-precision measurement of large parts and complex geometries.', 'Installiert ist die PRISMO VAST 09/24/07 für hochpräzise Messungen an großen Bauteilen und komplexen Geometrien.'],
  ['Além da medição tátil, o recurso LineScan permite capturar superfícies como nuvens de pontos, apoiando inspeção de forma e comparação com modelos CAD.', 'In addition to tactile measurement, LineScan captures surfaces as point clouds to support form inspection and comparison with CAD models.', 'Neben der taktilen Messung erfasst LineScan Oberflächen als Punktwolken und unterstützt Formprüfung sowie den Vergleich mit CAD-Modellen.'],
  ['Componentes automotivos e de precisão', 'Automotive and precision components', 'Automobil- und Präzisionskomponenten'],
  ['Medição de engrenagens e superfícies complexas', 'Measurement of gears and complex surfaces', 'Messung von Zahnrädern und komplexen Oberflächen'],
  ['Validação de protótipos e ferramentais', 'Validation of prototypes and tooling', 'Validierung von Prototypen und Werkzeugen'],
  ['Inspeções com tolerâncias rigorosas', 'Inspections with tight tolerances', 'Prüfungen mit engen Toleranzen'],
  ['Configuração instalada: PRISMO VAST 09/24/07', 'Installed configuration: PRISMO VAST 09/24/07', 'Installierte Konfiguration: PRISMO VAST 09/24/07'],
  ['Medição de alta precisão para peças grandes e complexas', 'High-precision measurement for large and complex parts', 'Hochpräzise Messung großer und komplexer Bauteile'],
  ['LineScan para captura de superfícies em nuvens de pontos', 'LineScan for capturing surfaces as point clouds', 'LineScan zur Erfassung von Oberflächen als Punktwolken'],
  ['Escalas de vitrocerâmica Robax com resolução informada de 200 nm', 'Robax glass-ceramic scales with a specified resolution of 200 nm', 'Robax-Glaskeramikmaßstäbe mit angegebener Auflösung von 200 nm'],
  ['Dimensão, forma e posição', 'Dimension, form and position', 'Maß, Form und Lage'],
  ['Perfis de linha e superfície', 'Line and surface profiles', 'Linien- und Flächenprofile'],
  ['Geometrias livres', 'Freeform geometries', 'Freiformgeometrien'],
  ['Avaliação de desvios em relação ao CAD', 'Evaluation of deviations from CAD', 'Bewertung von Abweichungen zum CAD'],
  ['Alta precisão e estabilidade', 'High accuracy and stability', 'Hohe Genauigkeit und Stabilität'],
  ['Varredura ativa com sensores VAST', 'Active scanning with VAST sensors', 'Aktives Scanning mit VAST-Sensoren'],
  ['Produtividade em programas complexos', 'Productivity in complex measurement programs', 'Produktivität bei komplexen Messprogrammen'],
  ['Ampla flexibilidade de sensores e acessórios', 'Broad flexibility of sensors and accessories', 'Hohe Flexibilität bei Sensoren und Zubehör'],
  ['O cartaz local identifica a configuração PRISMO VAST 09/24/07 e informa uma expressão de precisão com L/350 µm. A fórmula completa, os sensores disponíveis e as condições de validade devem ser confirmados com a equipe antes de constarem na proposta.', 'The local notice identifies the PRISMO VAST 09/24/07 configuration and provides an accuracy expression containing L/350 µm. The complete formula, available sensors and validity conditions must be confirmed with the team before inclusion in a proposal.', 'Der lokale Aushang nennt die Konfiguration PRISMO VAST 09/24/07 und eine Genauigkeitsangabe mit L/350 µm. Die vollständige Formel, verfügbare Sensoren und Gültigkeitsbedingungen müssen vor Aufnahme in ein Angebot mit dem Team bestätigt werden.'],

  ['Raios X e inspeção não destrutiva', 'X-ray and non-destructive inspection', 'Röntgen- und zerstörungsfreie Prüfung'],
  ['Sistema de raios X para detectar e avaliar descontinuidades internas sem seccionar a peça.', 'X-ray system for detecting and evaluating internal discontinuities without sectioning the part.', 'Röntgensystem zur Erkennung und Bewertung innerer Unregelmäßigkeiten ohne Zerstörung des Bauteils.'],
  ['A configuração instalada no Centro é a BOSELLO MAX 80-150, um sistema de raios X 2D para inspeção não destrutiva de peças e conjuntos.', 'The Center operates a BOSELLO MAX 80-150, a 2D X-ray system for non-destructive inspection of parts and assemblies.', 'Im Zentrum ist eine BOSELLO MAX 80-150 installiert, ein 2D-Röntgensystem zur zerstörungsfreien Prüfung von Bauteilen und Baugruppen.'],
  ['O equipamento examina estruturas internas sem danificar a peça, apoia reconhecimento automático de defeitos e é preparado para adquirir conjuntos de imagens destinados à geração de modelos 3D de peças fundidas.', 'The system examines internal structures without damaging the part, supports automatic defect recognition and is prepared to acquire image sets for generating 3D models of cast parts.', 'Das System untersucht innere Strukturen zerstörungsfrei, unterstützt automatische Fehlererkennung und ist für Bildserien zur Erzeugung von 3D-Modellen von Gussteilen vorbereitet.'],
  ['Fundidos e componentes automotivos', 'Castings and automotive components', 'Gussteile und Automobilkomponenten'],
  ['Peças montadas e conjuntos', 'Assembled parts and assemblies', 'Montierte Bauteile und Baugruppen'],
  ['Investigação de porosidade e inclusões', 'Investigation of porosity and inclusions', 'Untersuchung von Porosität und Einschlüssen'],
  ['Análise de falhas internas', 'Analysis of internal failures', 'Analyse innerer Fehler'],
  ['Inspeção radiográfica por raios X 2D', '2D X-ray radiographic inspection', 'Radiografische 2D-Röntgenprüfung'],
  ['Exame interno sem danificar a peça', 'Internal examination without damaging the part', 'Innenprüfung ohne Beschädigung des Bauteils'],
  ['Reconhecimento automático de defeitos para diferentes aplicações', 'Automatic defect recognition for different applications', 'Automatische Fehlererkennung für verschiedene Anwendungen'],
  ['Sistema CT-ready para adquirir imagens destinadas a modelos 3D de fundidos', 'CT-ready system for acquiring images intended for 3D models of castings', 'CT-fähiges System zur Aufnahme von Bildern für 3D-Modelle von Gussteilen'],
  ['Detecção de descontinuidades', 'Detection of discontinuities', 'Erkennung von Unregelmäßigkeiten'],
  ['Avaliação de montagem interna', 'Evaluation of internal assembly', 'Bewertung innerer Montagezustände'],
  ['Investigação de falhas', 'Failure investigation', 'Fehleruntersuchung'],
  ['Comparação qualitativa e dimensional de projeções', 'Qualitative and dimensional comparison of projections', 'Qualitativer und dimensionaler Vergleich von Projektionen'],
  ['Ensaio não destrutivo', 'Non-destructive testing', 'Zerstörungsfreie Prüfung'],
  ['Visualização de características ocultas', 'Visualization of hidden features', 'Visualisierung verborgener Merkmale'],
  ['Configuração adaptável à aplicação', 'Configuration adaptable to the application', 'An die Anwendung anpassbare Konfiguration'],
  ['Apoio a triagem e investigação de causa', 'Support for screening and root-cause investigation', 'Unterstützung bei Sichtung und Ursachenanalyse'],
  ['Configuração identificada no Centro: BOSELLO MAX 80-150. A viabilidade radiográfica e a geração de modelos 3D dependem de material, espessura, geometria, energia e estratégia de aquisição.', 'Configuration identified at the Center: BOSELLO MAX 80-150. Radiographic feasibility and generation of 3D models depend on material, thickness, geometry, energy and acquisition strategy.', 'Im Zentrum identifizierte Konfiguration: BOSELLO MAX 80-150. Die radiografische Eignung und die Erzeugung von 3D-Modellen hängen von Material, Dicke, Geometrie, Energie und Aufnahmestrategie ab.'],

  ['Digitalização óptica 3D', '3D optical scanning', 'Optisches 3D-Scannen'],
  ['Scanner industrial de luz azul estruturada para captura de superfícies, inspeção e engenharia reversa.', 'Industrial structured blue-light scanner for surface capture, inspection and reverse engineering.', 'Industrieller Streifenlichtscanner mit blauem Licht für Oberflächenerfassung, Prüfung und Reverse Engineering.'],
  ['O ATOS Q digitaliza superfícies sem contato e gera dados tridimensionais densos para inspeção de forma, comparação nominal-real e documentação dimensional.', 'ATOS Q scans surfaces without contact and generates dense three-dimensional data for form inspection, nominal-to-actual comparison and dimensional documentation.', 'ATOS Q digitalisiert Oberflächen berührungslos und erzeugt dichte dreidimensionale Daten für Formprüfung, Soll-Ist-Vergleich und Maßdokumentation.'],
  ['Seu formato compacto favorece aplicações manuais ou semiautomatizadas, atendendo peças pequenas e médias com diferentes áreas de medição.', 'Its compact design supports manual or semi-automated applications for small and medium-sized parts using different measuring areas.', 'Die kompakte Bauform unterstützt manuelle oder teilautomatisierte Anwendungen für kleine und mittlere Bauteile mit unterschiedlichen Messbereichen.'],
  ['Inspeção de peças plásticas, fundidas e estampadas', 'Inspection of plastic, cast and stamped parts', 'Prüfung von Kunststoff-, Guss- und Stanzteilen'],
  ['Engenharia reversa', 'Reverse engineering', 'Reverse Engineering'],
  ['Desenvolvimento de produto e try-out', 'Product development and try-out', 'Produktentwicklung und Try-out'],
  ['Controle de manufatura aditiva', 'Additive manufacturing inspection', 'Prüfung additiver Fertigung'],
  ['Aquisição de até 8 milhões de pontos por varredura na versão 8M', 'Acquisition of up to 8 million points per scan in the 8M version', 'Erfassung von bis zu 8 Millionen Punkten pro Scan in der 8M-Version'],
  ['Áreas de medição intercambiáveis', 'Interchangeable measuring areas', 'Austauschbare Messbereiche'],
  ['Luz azul estruturada e princípio Triple Scan', 'Structured blue light and Triple Scan principle', 'Strukturiertes Blaulicht und Triple-Scan-Prinzip'],
  ['Fluxo de inspeção e relatórios no ZEISS INSPECT', 'Inspection workflow and reports in ZEISS INSPECT', 'Prüfablauf und Berichte in ZEISS INSPECT'],
  ['Mapa de desvios nominal-real', 'Nominal-to-actual deviation map', 'Soll-Ist-Abweichungskarte'],
  ['GD&T em dados de superfície', 'GD&T on surface data', 'GPS/GD&T auf Oberflächendaten'],
  ['Espessuras, seções e recortes', 'Thicknesses, sections and cutouts', 'Dicken, Schnitte und Ausschnitte'],
  ['Malha poligonal para engenharia reversa', 'Polygon mesh for reverse engineering', 'Polygonnetz für Reverse Engineering'],
  ['Medição de campo completo sem contato', 'Full-field non-contact measurement', 'Berührungslose Vollfeldmessung'],
  ['Mobilidade e configuração flexível', 'Mobility and flexible configuration', 'Mobilität und flexible Konfiguration'],
  ['Monitoramento da qualidade dos dados', 'Data quality monitoring', 'Überwachung der Datenqualität'],
  ['Boa cobertura de geometrias complexas', 'Good coverage of complex geometries', 'Gute Abdeckung komplexer Geometrien'],
  ['A versão instalada é ATOS Q 8M. Área de medição, lentes, preparação superficial e estratégia são definidas conforme o tamanho, acabamento e precisão requerida.', 'The installed version is ATOS Q 8M. Measuring area, lenses, surface preparation and strategy are defined according to size, finish and required accuracy.', 'Installiert ist die ATOS Q 8M. Messbereich, Objektive, Oberflächenvorbereitung und Strategie werden nach Größe, Oberfläche und erforderlicher Genauigkeit festgelegt.'],

  ['Scanner laser 3D portátil', 'Portable 3D laser scanner', 'Tragbarer 3D-Laserscanner'],
  ['Scanner laser manual para capturar peças e estruturas no local, com mobilidade e precisão metrológica.', 'Handheld laser scanner for capturing parts and structures on site with mobility and metrology-grade accuracy.', 'Handgeführter Laserscanner zur mobilen, messtechnisch genauen Erfassung von Bauteilen und Strukturen vor Ort.'],
  ['O T-SCAN hawk 2 permite digitalização 3D portátil em peças que não podem ser levadas a uma máquina fixa ou que exigem liberdade de acesso.', 'T-SCAN hawk 2 enables portable 3D scanning of parts that cannot be taken to a stationary machine or require unrestricted access.', 'T-SCAN hawk 2 ermöglicht mobiles 3D-Scannen von Bauteilen, die nicht zu einer stationären Maschine gebracht werden können oder freien Zugang erfordern.'],
  ['Modos de captura para detalhes, cavidades e objetos maiores apoiam inspeção, manutenção e engenharia reversa em diferentes ambientes.', 'Capture modes for details, cavities and larger objects support inspection, maintenance and reverse engineering in different environments.', 'Erfassungsmodi für Details, Kavitäten und größere Objekte unterstützen Prüfung, Instandhaltung und Reverse Engineering in unterschiedlichen Umgebungen.'],
  ['Engenharia reversa de peças e estruturas', 'Reverse engineering of parts and structures', 'Reverse Engineering von Bauteilen und Strukturen'],
  ['Inspeção no local', 'On-site inspection', 'Prüfung vor Ort'],
  ['Manutenção, reparo e revisão', 'Maintenance, repair and overhaul', 'Wartung, Reparatur und Überholung'],
  ['Digitalização de geometrias grandes ou de difícil acesso', 'Scanning of large or hard-to-reach geometries', 'Digitalisierung großer oder schwer zugänglicher Geometrien'],
  ['Scanner laser azul de classe 2', 'Class 2 blue laser scanner', 'Blaulicht-Laserscanner der Klasse 2'],
  ['Operação manual com aproximadamente 1 kg', 'Handheld operation at approximately 1 kg', 'Handgeführter Betrieb bei etwa 1 kg Gewicht'],
  ['Modo satélite para objetos maiores', 'Satellite mode for larger objects', 'Satellitenmodus für größere Objekte'],
  ['Captura de detalhes e cavidades profundas', 'Capture of details and deep cavities', 'Erfassung von Details und tiefen Kavitäten'],
  ['Nuvem de pontos e malha 3D', 'Point cloud and 3D mesh', 'Punktwolke und 3D-Netz'],
  ['Comparação com CAD', 'Comparison with CAD', 'Vergleich mit CAD'],
  ['Inspeção de superfície', 'Surface inspection', 'Oberflächenprüfung'],
  ['Aquisição para reconstrução geométrica', 'Acquisition for geometric reconstruction', 'Erfassung zur geometrischen Rekonstruktion'],
  ['Portabilidade', 'Portability', 'Portabilität'],
  ['Controle do fluxo pelo próprio scanner', 'Workflow control directly on the scanner', 'Ablaufsteuerung direkt am Scanner'],
  ['Uso em peças de diferentes portes', 'Use on parts of different sizes', 'Einsatz an Bauteilen unterschiedlicher Größe'],
  ['Rapidez de preparação e aquisição', 'Fast setup and acquisition', 'Schnelle Vorbereitung und Erfassung'],
  ['Precisão, quantidade de marcadores e estratégia dependem do volume e das condições de captura. A equipe confirma a abordagem após analisar a peça e a finalidade.', 'Accuracy, number of markers and strategy depend on the volume and capture conditions. The team confirms the approach after reviewing the part and its purpose.', 'Genauigkeit, Anzahl der Marker und Strategie hängen vom Volumen und den Aufnahmebedingungen ab. Das Team bestätigt den Ansatz nach Prüfung des Bauteils und seines Zwecks.'],

  ['Equipamento em fundo branco', 'Machine on a white background', 'Maschine vor weißem Hintergrund'],
  ['Equipamento instalado no Centro', 'Machine installed at the Center', 'Im Zentrum installierte Maschine'],
  ['Equipamento em operação', 'Machine in operation', 'Maschine im Betrieb'],
  ['Máquina de medição por coordenadas ZEISS DuraMax HTG 5/5/5 em fundo branco', 'ZEISS DuraMax HTG 5/5/5 coordinate measuring machine on a white background', 'Koordinatenmessgerät ZEISS DuraMax HTG 5/5/5 vor weißem Hintergrund'],
  ['ZEISS DuraMax instalada no Centro de Excelência em Metrologia', 'ZEISS DuraMax installed at the Metrology Center of Excellence', 'ZEISS DuraMax im Kompetenzzentrum für Messtechnik'],
  ['Vídeo da ZEISS DuraMax em operação', 'Video of the ZEISS DuraMax in operation', 'Video der ZEISS DuraMax im Betrieb'],
  ['Máquina multissensor ZEISS O-INSPECT em fundo branco', 'ZEISS O-INSPECT multisensor machine on a white background', 'ZEISS O-INSPECT Multisensor-Messgerät vor weißem Hintergrund'],
  ['ZEISS O-INSPECT instalada no laboratório', 'ZEISS O-INSPECT installed in the laboratory', 'ZEISS O-INSPECT im Labor'],
  ['Vídeo da ZEISS O-INSPECT em operação', 'Video of the ZEISS O-INSPECT in operation', 'Video der ZEISS O-INSPECT im Betrieb'],
  ['Máquina de medição por coordenadas ZEISS PRISMO em fundo branco', 'ZEISS PRISMO coordinate measuring machine on a white background', 'Koordinatenmessgerät ZEISS PRISMO vor weißem Hintergrund'],
  ['ZEISS PRISMO instalada no Centro', 'ZEISS PRISMO installed at the Center', 'ZEISS PRISMO im Zentrum'],
  ['Sistema de raios X ZEISS BOSELLO MAX 80-150 completo em fundo branco', 'Complete ZEISS BOSELLO MAX 80-150 X-ray system on a white background', 'Vollständiges Röntgensystem ZEISS BOSELLO MAX 80-150 vor weißem Hintergrund'],
  ['ZEISS BOSELLO MAX instalada no Centro', 'ZEISS BOSELLO MAX installed at the Center', 'ZEISS BOSELLO MAX im Zentrum'],
  ['Vídeo da ZEISS BOSELLO MAX em operação', 'Video of the ZEISS BOSELLO MAX in operation', 'Video der ZEISS BOSELLO MAX im Betrieb'],
  ['Scanner industrial ZEISS ATOS Q em fundo branco', 'ZEISS ATOS Q industrial scanner on a white background', 'Industriescanner ZEISS ATOS Q vor weißem Hintergrund'],
  ['ZEISS ATOS Q instalada no Centro', 'ZEISS ATOS Q installed at the Center', 'ZEISS ATOS Q im Zentrum'],
  ['Vídeo do ZEISS ATOS Q em operação', 'Video of the ZEISS ATOS Q in operation', 'Video des ZEISS ATOS Q im Betrieb'],
  ['Scanner portátil ZEISS T-SCAN hawk 2 completo em fundo branco', 'Complete ZEISS T-SCAN hawk 2 portable scanner on a white background', 'Vollständiger tragbarer Scanner ZEISS T-SCAN hawk 2 vor weißem Hintergrund'],
  ['Close-up do ZEISS T-SCAN hawk 2 no Centro', 'Close-up of the ZEISS T-SCAN hawk 2 at the Center', 'Nahaufnahme des ZEISS T-SCAN hawk 2 im Zentrum'],
] as const satisfies readonly TrioTraducao[];
