-- Publica as mídias reais autorizadas dos setores e as novidades fornecidas pela equipe.

do $$
declare
  item record;
  conteudo_id_encontrado uuid;
  versao_id_encontrada uuid;
begin
  select id into conteudo_id_encontrado from conteudos where chave = 'inicio.setores';
  if conteudo_id_encontrado is null then
    raise exception 'O conteúdo inicio.setores deve existir antes da migration 047.';
  end if;

  for item in select * from (values
    ('pt-BR','Soluções organizadas por setor','Escolha o cenário mais próximo da sua empresa e navegue por aplicações reais do Centro.',
      '[{"slug":"industria-geral","midias":[{"tipo":"video","src":"/videos/setor-industria-medicao-bomba-tomate.mp4","alt":"Medição dos cilindros internos de uma bomba de extrato de tomate","legenda":"Verificação dimensional dos cilindros internos de uma bomba industrial"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-componentes.jpeg","alt":"Componentes desmontados de bombas de extrato de tomate organizados para inspeção","legenda":"Componentes de bombas industriais preparados para medição"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-conjunto.jpeg","alt":"Conjunto de bombas de extrato de tomate após o trabalho dimensional","legenda":"Conjunto industrial atendido pelo Centro de Excelência em Metrologia"}]},{"slug":"automotivo-mobilidade","midias":[{"tipo":"video","src":"/videos/setor-automotivo-borboleta-scan-cad.mp4","alt":"Digitalização de uma borboleta de admissão para reconstrução CAD","legenda":"Da peça física ao CAD em uma aplicação automotiva"},{"tipo":"imagem","src":"/imagens/setor-automotivo-veiculo.png","alt":"Automóvel clássico que recebeu o conjunto de admissão analisado","legenda":"Aplicação automotiva do projeto de engenharia reversa"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-instalada.png","alt":"Borboleta de admissão instalada no motor do automóvel","legenda":"Componente de admissão instalado no veículo"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-admissao.png","alt":"Borboleta de admissão automotiva isolada em fundo branco","legenda":"Geometria da borboleta de admissão usada no projeto"}]},{"slug":"aeronautico","midias":[{"tipo":"video","src":"/videos/setor-aeronautico-peca-aviao.mp4","alt":"Inspeção de uma peça aeronáutica no Centro","legenda":"Metrologia aplicada a um componente aeronáutico"},{"tipo":"video","src":"/videos/setor-aeronautico-aviao.mp4","alt":"Aeronave relacionada à aplicação de metrologia","legenda":"Contexto de aplicação no setor aeronáutico"}]},{"slug":"ferramentaria-produto","midias":[{"tipo":"video","src":"/videos/setor-ferramentaria-engenharia-reversa-engrenagem.mp4","alt":"Engenharia reversa de uma engrenagem para ferramentaria","legenda":"Reconstrução digital de engrenagem para desenvolvimento de produto"}]}]'::jsonb),
    ('en','Solutions organized by industry','Choose the context closest to your company and browse real applications from the Center.',
      '[{"slug":"industria-geral","midias":[{"tipo":"video","src":"/videos/setor-industria-medicao-bomba-tomate.mp4","alt":"Measurement of the internal cylinders of a tomato paste pump","legenda":"Dimensional inspection of the internal cylinders of an industrial pump"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-componentes.jpeg","alt":"Disassembled tomato paste pump components arranged for inspection","legenda":"Industrial pump components prepared for measurement"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-conjunto.jpeg","alt":"Tomato paste pump assemblies after dimensional work","legenda":"Industrial assembly supported by the Metrology Center of Excellence"}]},{"slug":"automotivo-mobilidade","midias":[{"tipo":"video","src":"/videos/setor-automotivo-borboleta-scan-cad.mp4","alt":"Scanning an intake throttle body for CAD reconstruction","legenda":"From the physical part to CAD in an automotive application"},{"tipo":"imagem","src":"/imagens/setor-automotivo-veiculo.png","alt":"Classic car fitted with the analyzed intake assembly","legenda":"Automotive application of the reverse engineering project"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-instalada.png","alt":"Intake throttle body installed in the vehicle engine","legenda":"Intake component installed in the vehicle"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-admissao.png","alt":"Automotive intake throttle body isolated on a white background","legenda":"Throttle body geometry used in the project"}]},{"slug":"aeronautico","midias":[{"tipo":"video","src":"/videos/setor-aeronautico-peca-aviao.mp4","alt":"Inspection of an aerospace part at the Center","legenda":"Metrology applied to an aerospace component"},{"tipo":"video","src":"/videos/setor-aeronautico-aviao.mp4","alt":"Aircraft related to the metrology application","legenda":"Application context in the aerospace sector"}]},{"slug":"ferramentaria-produto","midias":[{"tipo":"video","src":"/videos/setor-ferramentaria-engenharia-reversa-engrenagem.mp4","alt":"Reverse engineering of a gear for tooling","legenda":"Digital reconstruction of a gear for product development"}]}]'::jsonb),
    ('de','Lösungen nach Branchen','Wählen Sie den passenden Kontext für Ihr Unternehmen und sehen Sie reale Anwendungen des Zentrums an.',
      '[{"slug":"industria-geral","midias":[{"tipo":"video","src":"/videos/setor-industria-medicao-bomba-tomate.mp4","alt":"Messung der Innenzylinder einer Tomatenmarkpumpe","legenda":"Maßprüfung der Innenzylinder einer Industriepumpe"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-componentes.jpeg","alt":"Demontierte Komponenten von Tomatenmarkpumpen zur Prüfung angeordnet","legenda":"Komponenten von Industriepumpen für die Messung vorbereitet"},{"tipo":"imagem","src":"/imagens/setor-industria-bombas-tomate-conjunto.jpeg","alt":"Tomatenmarkpumpen nach der Maßprüfung","legenda":"Industriebaugruppe, die vom Kompetenzzentrum für Messtechnik betreut wurde"}]},{"slug":"automotivo-mobilidade","midias":[{"tipo":"video","src":"/videos/setor-automotivo-borboleta-scan-cad.mp4","alt":"Digitalisierung eines Drosselklappengehäuses zur CAD-Rekonstruktion","legenda":"Vom physischen Bauteil zum CAD-Modell in einer Automobilanwendung"},{"tipo":"imagem","src":"/imagens/setor-automotivo-veiculo.png","alt":"Klassischer Pkw mit der untersuchten Ansaugbaugruppe","legenda":"Automobilanwendung des Reverse-Engineering-Projekts"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-instalada.png","alt":"Im Fahrzeugmotor eingebautes Drosselklappengehäuse","legenda":"Im Fahrzeug eingebautes Ansaugbauteil"},{"tipo":"imagem","src":"/imagens/setor-automotivo-borboleta-admissao.png","alt":"Drosselklappengehäuse vor weißem Hintergrund","legenda":"Im Projekt verwendete Geometrie des Drosselklappengehäuses"}]},{"slug":"aeronautico","midias":[{"tipo":"video","src":"/videos/setor-aeronautico-peca-aviao.mp4","alt":"Prüfung eines Luftfahrtbauteils im Zentrum","legenda":"Messtechnik an einem Luftfahrtbauteil"},{"tipo":"video","src":"/videos/setor-aeronautico-aviao.mp4","alt":"Flugzeug im Zusammenhang mit der messtechnischen Anwendung","legenda":"Anwendungskontext in der Luftfahrt"}]},{"slug":"ferramentaria-produto","midias":[{"tipo":"video","src":"/videos/setor-ferramentaria-engenharia-reversa-engrenagem.mp4","alt":"Reverse Engineering eines Zahnrads für den Werkzeugbau","legenda":"Digitale Rekonstruktion eines Zahnrads für die Produktentwicklung"}]}]'::jsonb)
  ) sementes(idioma,titulo,texto,setores)
  loop
    insert into versoes_conteudo(conteudo_id,numero,idioma,titulo,corpo,estado_revisao)
    select conteudo_id_encontrado,coalesce(max(numero),0)+1,item.idioma,item.titulo,
      jsonb_build_object('texto',item.texto,'setores',item.setores),'aprovada'
    from versoes_conteudo where conteudo_id=conteudo_id_encontrado and idioma=item.idioma
    returning id into versao_id_encontrada;
    insert into publicacoes_conteudo(conteudo_id,idioma,versao_conteudo_id,publicada_em)
    values(conteudo_id_encontrado,item.idioma,versao_id_encontrada,now())
    on conflict(conteudo_id,idioma) do update set versao_conteudo_id=excluded.versao_conteudo_id,publicada_em=now();
    if item.idioma='pt-BR' then update conteudos set versao_publicada_id=versao_id_encontrada where id=conteudo_id_encontrado; end if;
  end loop;
end;
$$;

do $$
declare
  item record;
  conteudo_id_encontrado uuid;
  versao_id_encontrada uuid;
begin
  select id into conteudo_id_encontrado from conteudos where chave = 'inicio.acontecimentos';
  if conteudo_id_encontrado is null then
    raise exception 'O conteúdo inicio.acontecimentos deve existir antes da migration 047.';
  end if;

  for item in select * from (values
    ('pt-BR','Novidades no Centro','Eventos, projetos e próximos passos do Centro de Excelência em Metrologia.',
      '[{"tipo":"recente","data":"Agosto de 2026","titulo":"Congresso SINDAG","resumo":"O Centro apresentou suas capacidades e trocou experiências com profissionais do setor durante o congresso.","midias":[{"tipo":"imagem","src":"/imagens/evento-congresso-sindag-2026.jpeg","alt":"Equipe do Centro durante o Congresso SINDAG em agosto de 2026","legenda":"Participação no Congresso SINDAG — agosto de 2026"}]},{"tipo":"recente","data":"Setembro de 2026","titulo":"ExpoPeças 2026","resumo":"A equipe participou da feira para aproximar a metrologia avançada das demandas da indústria de componentes.","midias":[{"tipo":"imagem","src":"/imagens/evento-expopecas-2026.jpeg","alt":"Equipe reunida durante a ExpoPeças em setembro de 2026","legenda":"Participação na ExpoPeças — setembro de 2026"}]},{"tipo":"agora","data":"Em desenvolvimento","titulo":"Portal de acompanhamento ampliado","resumo":"O novo software está sendo construído para integrar solicitações, propostas, execução e comunicação com o cliente.","midias":[{"tipo":"video","src":"/videos/portal-acompanhamento-servicos.mp4","alt":"Demonstração do portal de acompanhamento dos serviços","legenda":"Software para acompanhamento ampliado dos serviços"}]},{"tipo":"proximo","data":"Próximo passo","titulo":"Caminho para a acreditação INMETRO","resumo":"O Centro trabalha na preparação de processos e evidências para avançar rumo à acreditação. A imagem desta etapa será publicada quando estiver disponível."}]'::jsonb),
    ('en','News from the Center','Events, projects and next steps from the Metrology Center of Excellence.',
      '[{"tipo":"recente","data":"August 2026","titulo":"SINDAG Congress","resumo":"The Center presented its capabilities and exchanged experience with industry professionals during the congress.","midias":[{"tipo":"imagem","src":"/imagens/evento-congresso-sindag-2026.jpeg","alt":"Center team at the SINDAG Congress in August 2026","legenda":"Participation in the SINDAG Congress — August 2026"}]},{"tipo":"recente","data":"September 2026","titulo":"ExpoPeças 2026","resumo":"The team attended the trade fair to bring advanced metrology closer to the needs of the components industry.","midias":[{"tipo":"imagem","src":"/imagens/evento-expopecas-2026.jpeg","alt":"Team gathered at ExpoPeças in September 2026","legenda":"Participation in ExpoPeças — September 2026"}]},{"tipo":"agora","data":"In development","titulo":"Expanded service tracking portal","resumo":"The new software is being built to integrate requests, proposals, execution and customer communication.","midias":[{"tipo":"video","src":"/videos/portal-acompanhamento-servicos.mp4","alt":"Demonstration of the service tracking portal","legenda":"Software for expanded service tracking"}]},{"tipo":"proximo","data":"Next step","titulo":"Path toward INMETRO accreditation","resumo":"The Center is preparing processes and evidence to move toward accreditation. An image of this stage will be published when available."}]'::jsonb),
    ('de','Neuigkeiten aus dem Zentrum','Veranstaltungen, Projekte und nächste Schritte des Kompetenzzentrums für Messtechnik.',
      '[{"tipo":"recente","data":"August 2026","titulo":"SINDAG-Kongress","resumo":"Das Zentrum stellte seine Kompetenzen vor und tauschte sich während des Kongresses mit Fachleuten der Branche aus.","midias":[{"tipo":"imagem","src":"/imagens/evento-congresso-sindag-2026.jpeg","alt":"Team des Zentrums auf dem SINDAG-Kongress im August 2026","legenda":"Teilnahme am SINDAG-Kongress — August 2026"}]},{"tipo":"recente","data":"September 2026","titulo":"ExpoPeças 2026","resumo":"Das Team nahm an der Fachmesse teil, um moderne Messtechnik näher an die Anforderungen der Komponentenindustrie zu bringen.","midias":[{"tipo":"imagem","src":"/imagens/evento-expopecas-2026.jpeg","alt":"Team auf der ExpoPeças im September 2026","legenda":"Teilnahme an der ExpoPeças — September 2026"}]},{"tipo":"agora","data":"In Entwicklung","titulo":"Erweitertes Portal zur Auftragsverfolgung","resumo":"Die neue Software wird entwickelt, um Anfragen, Angebote, Ausführung und Kundenkommunikation zu verbinden.","midias":[{"tipo":"video","src":"/videos/portal-acompanhamento-servicos.mp4","alt":"Demonstration des Portals zur Auftragsverfolgung","legenda":"Software zur erweiterten Auftragsverfolgung"}]},{"tipo":"proximo","data":"Nächster Schritt","titulo":"Weg zur INMETRO-Akkreditierung","resumo":"Das Zentrum bereitet Prozesse und Nachweise vor, um die Akkreditierung voranzutreiben. Ein Bild dieser Phase wird veröffentlicht, sobald es verfügbar ist."}]'::jsonb)
  ) sementes(idioma,titulo,texto,itens)
  loop
    insert into versoes_conteudo(conteudo_id,numero,idioma,titulo,corpo,estado_revisao)
    select conteudo_id_encontrado,coalesce(max(numero),0)+1,item.idioma,item.titulo,
      jsonb_build_object('texto',item.texto,'itens',item.itens),'aprovada'
    from versoes_conteudo where conteudo_id=conteudo_id_encontrado and idioma=item.idioma
    returning id into versao_id_encontrada;
    insert into publicacoes_conteudo(conteudo_id,idioma,versao_conteudo_id,publicada_em)
    values(conteudo_id_encontrado,item.idioma,versao_id_encontrada,now())
    on conflict(conteudo_id,idioma) do update set versao_conteudo_id=excluded.versao_conteudo_id,publicada_em=now();
    if item.idioma='pt-BR' then update conteudos set versao_publicada_id=versao_id_encontrada where id=conteudo_id_encontrado; end if;
  end loop;
end;
$$;

comment on table public.versoes_conteudo is
  'Versões editoriais; a migration 047 publica mídias reais autorizadas para setores e novidades nos três idiomas.';
