'use client';

import { Bot, Database, Eye, FileCheck2, LockKeyhole, Scale, ShieldCheck, UserRoundCheck } from 'lucide-react';
import { CabecalhoPublico } from '../../componentes/cabecalho-publico';
import { ContatoEmail } from '../../componentes/contato-email';
import { RodapePublico } from '../../componentes/rodape-publico';
import { useIdiomaPublico } from '../../lib/traducao-publica';
import '../publico.css';

const conteudos = {
  'pt-BR': {
    titulo: 'Privacidade e segurança',
    subtitulo: 'Entenda como o portal trata dados pessoais, protege informações e apoia um relacionamento transparente durante os serviços de metrologia.',
    compromissos: [
      ['Finalidade e necessidade', 'Coletamos somente os dados adequados e necessários para receber sua solicitação, preparar propostas, executar o serviço e manter a comunicação.'],
      ['Transparência e controle', 'Explicamos como os dados são utilizados e oferecemos canais para consulta, correção e exercício dos direitos previstos na LGPD.'],
      ['Segurança desde a concepção', 'O acesso é protegido por autenticação, perfis de permissão e separação dos registros de cada empresa.'],
    ],
    dados: { titulo: 'Quais dados podem ser tratados', itens: ['Dados de contato e da empresa, como nome, e-mail, telefone, função e CNPJ.', 'Informações da solicitação, proposta e execução do serviço.', 'Mensagens e arquivos técnicos enviados pelo cliente.', 'Dados necessários para autenticação, controle de acesso e rastreabilidade.'] },
    finalidades: { titulo: 'Para que utilizamos os dados', texto: 'O tratamento está ligado ao atendimento solicitado e às obrigações aplicáveis. As principais finalidades são:', itens: ['Identificar o solicitante e a empresa atendida;', 'Analisar a necessidade e elaborar propostas;', 'Planejar, executar, validar e documentar o serviço;', 'Permitir acompanhamento, troca de mensagens e entrega de documentos;', 'Preservar segurança, rastreabilidade e cumprimento de obrigações legais.'] },
    protecao: { titulo: 'Como protegemos as informações', texto: 'O portal adota camadas de proteção proporcionais ao contexto do serviço, incluindo controle por função, isolamento por empresa, arquivos privados e verificação de integridade de documentos. A segurança é acompanhada por testes e revisão contínua. Nenhum sistema elimina todos os riscos; por isso, também mantemos processos de prevenção, avaliação e resposta.' },
    compartilhamento: { titulo: 'Compartilhamento e conservação', texto: 'Os dados podem ser tratados por fornecedores tecnológicos indispensáveis à operação do portal, sempre dentro da finalidade do serviço e dos controles aplicáveis. Não comercializamos dados pessoais. As informações são conservadas pelo período necessário ao atendimento, à rastreabilidade e às obrigações legais ou institucionais. Pedidos de exclusão são avaliados considerando essas obrigações.' },
    ia: { titulo: 'Inteligência artificial e decisões', texto: 'Recursos de IA podem apoiar explicações e análises, mas não substituem a avaliação profissional nem aprovam ou recusam serviços de forma autônoma. Antes de qualquer integração, o portal é estruturado para remover identificadores, clientes, contatos, preços, margens e anexos. Recomendações permanecem sujeitas à revisão humana.' },
    direitos: { titulo: 'Seus direitos', texto: 'Nos termos da LGPD, o titular pode solicitar, conforme o caso, confirmação do tratamento, acesso, correção, informação sobre compartilhamento, portabilidade, anonimização, bloqueio ou eliminação de dados inadequados e revisão de decisões automatizadas. Também pode revogar o consentimento quando ele for a base aplicável. Algumas informações podem precisar ser mantidas por obrigação legal, regulatória ou para preservar a rastreabilidade do serviço.' },
    incidentes: { titulo: 'Prevenção e resposta a incidentes', texto: 'Se houver suspeita de incidente, a equipe responsável deve avaliar o caso, conter efeitos, preservar evidências e adotar as comunicações exigidas pela legislação. Quando um incidente confirmado puder causar risco ou dano relevante, a comunicação aos titulares e à ANPD seguirá os critérios e prazos aplicáveis, em linguagem clara e sem expor informações que aumentem o risco.' },
    etica: { titulo: 'Ética, confidencialidade e responsabilidade', texto: 'O tratamento deve respeitar finalidade, necessidade, transparência, segurança, prevenção, não discriminação e prestação de contas. O acesso às informações é limitado a quem precisa delas para realizar o atendimento. Resultados técnicos e recomendações devem ser interpretados por profissionais responsáveis, com cuidado para não extrapolar a finalidade informada ao cliente.' },
    referencias: { titulo: 'Referências e contato', texto: 'Este aviso resume práticas do portal e não substitui instrumentos contratuais nem orientações institucionais específicas. Para conhecer a legislação ou exercer seus direitos, consulte as referências oficiais e entre em contato com a equipe.', lgpd: 'Lei Geral de Proteção de Dados Pessoais — LGPD', anpd: 'Direitos dos titulares — ANPD' },
  },
  en: {
    titulo: 'Privacy and security', subtitulo: 'Learn how the portal processes personal data, protects information and supports a transparent relationship throughout metrology services.',
    compromissos: [['Purpose and necessity', 'We collect only data that is suitable and necessary to receive your request, prepare proposals, perform the service and communicate with you.'], ['Transparency and control', 'We explain how data is used and provide channels for access, correction and the exercise of rights under Brazilian data protection law.'], ['Security by design', 'Access is protected by authentication, permission profiles and separation of each company’s records.']],
    dados: { titulo: 'Data that may be processed', itens: ['Contact and company data, such as name, email, phone, role and Brazilian company registration number.', 'Request, proposal and service execution information.', 'Messages and technical files submitted by the customer.', 'Data required for authentication, access control and traceability.'] },
    finalidades: { titulo: 'Why we use data', texto: 'Processing is connected to the requested service and applicable obligations. Main purposes include:', itens: ['Identifying the requester and the customer company;', 'Reviewing the need and preparing proposals;', 'Planning, performing, validating and documenting the service;', 'Enabling tracking, messages and document delivery;', 'Preserving security, traceability and legal compliance.'] },
    protecao: { titulo: 'How information is protected', texto: 'The portal uses protection layers proportionate to the service context, including role-based access, company isolation, private files and document integrity checks. Security is supported by testing and continuous review. No system eliminates every risk, so prevention, assessment and response processes are also maintained.' },
    compartilhamento: { titulo: 'Sharing and retention', texto: 'Data may be processed by technology providers that are necessary to operate the portal, within the service purpose and applicable controls. We do not sell personal data. Information is retained as needed for service, traceability and legal or institutional duties. Deletion requests are assessed against those duties.' },
    ia: { titulo: 'Artificial intelligence and decisions', texto: 'AI features may support explanations and analysis, but they do not replace professional review or autonomously approve or reject services. Before any integration, the portal is designed to remove identifiers, customers, contacts, prices, margins and attachments. Recommendations remain subject to human review.' },
    direitos: { titulo: 'Your rights', texto: 'Under Brazilian data protection law, data subjects may request, as applicable, confirmation, access, correction, sharing information, portability, anonymization, blocking or deletion of inadequate data, and review of automated decisions. Consent may be withdrawn when it is the applicable legal basis. Some information may need to be retained for legal or regulatory duties or service traceability.' },
    incidentes: { titulo: 'Incident prevention and response', texto: 'If an incident is suspected, the responsible team must assess it, contain its effects, preserve evidence and make legally required communications. When a confirmed incident may cause relevant risk or damage, notices to data subjects and the ANPD will follow applicable criteria and deadlines in clear language, without disclosing information that increases risk.' },
    etica: { titulo: 'Ethics, confidentiality and accountability', texto: 'Processing must respect purpose, necessity, transparency, security, prevention, non-discrimination and accountability. Information is limited to people who need it to provide the service. Technical results and recommendations must be interpreted by responsible professionals and kept within the purpose explained to the customer.' },
    referencias: { titulo: 'References and contact', texto: 'This notice summarizes portal practices and does not replace contracts or specific institutional guidance. Use the official references below and contact the team to exercise your rights.', lgpd: 'Brazilian General Data Protection Law — LGPD', anpd: 'Data subject rights — ANPD' },
  },
  de: {
    titulo: 'Datenschutz und Sicherheit', subtitulo: 'Erfahren Sie, wie das Portal personenbezogene Daten verarbeitet, Informationen schützt und eine transparente Zusammenarbeit während messtechnischer Dienstleistungen unterstützt.',
    compromissos: [['Zweck und Erforderlichkeit', 'Wir erheben nur Daten, die für Ihre Anfrage, die Angebotserstellung, die Leistungserbringung und die Kommunikation erforderlich sind.'], ['Transparenz und Kontrolle', 'Wir erläutern die Datennutzung und bieten Kanäle für Auskunft, Berichtigung und die Ausübung der Rechte nach brasilianischem Datenschutzrecht.'], ['Datenschutz durch Technikgestaltung', 'Der Zugang wird durch Authentifizierung, Berechtigungsprofile und die Trennung der Unternehmensdaten geschützt.']],
    dados: { titulo: 'Welche Daten verarbeitet werden können', itens: ['Kontakt- und Unternehmensdaten wie Name, E-Mail, Telefon, Funktion und brasilianische Unternehmensnummer.', 'Informationen zu Anfrage, Angebot und Leistungserbringung.', 'Nachrichten und technische Dateien des Kunden.', 'Für Authentifizierung, Zugriffskontrolle und Nachvollziehbarkeit erforderliche Daten.'] },
    finalidades: { titulo: 'Wofür wir Daten verwenden', texto: 'Die Verarbeitung steht mit der angeforderten Leistung und den geltenden Pflichten in Verbindung. Hauptzwecke sind:', itens: ['Identifikation des Anfragenden und des Kundenunternehmens;', 'Prüfung des Bedarfs und Erstellung von Angeboten;', 'Planung, Durchführung, Validierung und Dokumentation der Leistung;', 'Statusverfolgung, Nachrichten und Dokumentenbereitstellung;', 'Sicherheit, Nachvollziehbarkeit und Erfüllung gesetzlicher Pflichten.'] },
    protecao: { titulo: 'Wie Informationen geschützt werden', texto: 'Das Portal verwendet dem Leistungskontext angemessene Schutzebenen, darunter rollenbasierte Zugriffe, Trennung nach Unternehmen, private Dateien und Integritätsprüfungen für Dokumente. Tests und kontinuierliche Überprüfungen unterstützen die Sicherheit. Kein System beseitigt alle Risiken; deshalb bestehen auch Verfahren für Prävention, Bewertung und Reaktion.' },
    compartilhamento: { titulo: 'Weitergabe und Aufbewahrung', texto: 'Daten können durch für den Portalbetrieb erforderliche Technologieanbieter verarbeitet werden, innerhalb des Leistungszwecks und der geltenden Kontrollen. Personenbezogene Daten werden nicht verkauft. Informationen werden nur so lange aufbewahrt, wie es für Leistung, Nachvollziehbarkeit sowie gesetzliche oder institutionelle Pflichten erforderlich ist. Löschanträge werden unter Berücksichtigung dieser Pflichten geprüft.' },
    ia: { titulo: 'Künstliche Intelligenz und Entscheidungen', texto: 'KI-Funktionen können Erklärungen und Analysen unterstützen, ersetzen jedoch keine fachliche Prüfung und genehmigen oder verweigern Leistungen nicht autonom. Vor einer Integration ist das Portal darauf ausgelegt, Identifikatoren, Kunden, Kontakte, Preise, Margen und Anhänge zu entfernen. Empfehlungen unterliegen der menschlichen Prüfung.' },
    direitos: { titulo: 'Ihre Rechte', texto: 'Nach brasilianischem Datenschutzrecht können betroffene Personen je nach Fall Bestätigung, Auskunft, Berichtigung, Informationen zur Weitergabe, Übertragbarkeit, Anonymisierung, Sperrung oder Löschung unangemessener Daten sowie die Überprüfung automatisierter Entscheidungen verlangen. Eine Einwilligung kann widerrufen werden, wenn sie die maßgebliche Rechtsgrundlage ist. Gesetzliche, regulatorische oder Nachvollziehbarkeitspflichten können eine weitere Aufbewahrung erfordern.' },
    incidentes: { titulo: 'Prävention und Reaktion bei Vorfällen', texto: 'Bei Verdacht auf einen Vorfall bewertet das zuständige Team den Fall, begrenzt Auswirkungen, sichert Nachweise und nimmt gesetzlich erforderliche Meldungen vor. Kann ein bestätigter Vorfall ein relevantes Risiko oder einen Schaden verursachen, erfolgen Mitteilungen an Betroffene und ANPD nach den geltenden Kriterien und Fristen in klarer Sprache, ohne risikosteigernde Details offenzulegen.' },
    etica: { titulo: 'Ethik, Vertraulichkeit und Verantwortung', texto: 'Die Verarbeitung beachtet Zweck, Erforderlichkeit, Transparenz, Sicherheit, Prävention, Nichtdiskriminierung und Rechenschaftspflicht. Informationen erhalten nur Personen, die sie für die Leistung benötigen. Technische Ergebnisse und Empfehlungen werden von verantwortlichen Fachkräften und innerhalb des dem Kunden erläuterten Zwecks interpretiert.' },
    referencias: { titulo: 'Referenzen und Kontakt', texto: 'Dieser Hinweis fasst die Praktiken des Portals zusammen und ersetzt weder Verträge noch besondere institutionelle Vorgaben. Nutzen Sie die offiziellen Quellen und kontaktieren Sie das Team, um Ihre Rechte auszuüben.', lgpd: 'Brasilianisches Datenschutzgesetz — LGPD', anpd: 'Rechte betroffener Personen — ANPD' },
  },
} as const;

const iconesCompromissos = [FileCheck2, Eye, ShieldCheck];

export default function Privacidade() {
  const idioma = useIdiomaPublico();
  const conteudo = conteudos[idioma];
  return <main>
    <CabecalhoPublico titulo={conteudo.titulo} texto={conteudo.subtitulo} />
    <article className="conteudo-publico privacidade">
      <section className="privacidade-compromissos" aria-label={conteudo.titulo}>{conteudo.compromissos.map(([titulo, texto], indice) => { const Icone = iconesCompromissos[indice] ?? ShieldCheck; return <article key={titulo}><Icone size={30} aria-hidden="true" /><h2>{titulo}</h2><p>{texto}</p></article>; })}</section>
      <div className="privacidade-grade">
        <section className="privacidade-bloco"><h2><Database size={24} aria-hidden="true" />{conteudo.dados.titulo}</h2><ul>{conteudo.dados.itens.map((item) => <li key={item}>{item}</li>)}</ul></section>
        <section className="privacidade-bloco"><h2><UserRoundCheck size={24} aria-hidden="true" />{conteudo.finalidades.titulo}</h2><p>{conteudo.finalidades.texto}</p><ul>{conteudo.finalidades.itens.map((item) => <li key={item}>{item}</li>)}</ul></section>
        <section className="privacidade-bloco"><h2><LockKeyhole size={24} aria-hidden="true" />{conteudo.protecao.titulo}</h2><p>{conteudo.protecao.texto}</p></section>
        <section className="privacidade-bloco"><h2><FileCheck2 size={24} aria-hidden="true" />{conteudo.compartilhamento.titulo}</h2><p>{conteudo.compartilhamento.texto}</p></section>
        <section className="privacidade-bloco"><h2><Bot size={24} aria-hidden="true" />{conteudo.ia.titulo}</h2><p>{conteudo.ia.texto}</p></section>
        <section className="privacidade-bloco"><h2><Scale size={24} aria-hidden="true" />{conteudo.direitos.titulo}</h2><p>{conteudo.direitos.texto}</p></section>
        <section className="privacidade-bloco"><h2><ShieldCheck size={24} aria-hidden="true" />{conteudo.incidentes.titulo}</h2><p>{conteudo.incidentes.texto}</p></section>
        <section className="privacidade-bloco"><h2><Eye size={24} aria-hidden="true" />{conteudo.etica.titulo}</h2><p>{conteudo.etica.texto}</p></section>
      </div>
      <section className="privacidade-referencias"><h2>{conteudo.referencias.titulo}</h2><p>{conteudo.referencias.texto}</p><ul><li><a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank" rel="noreferrer">{conteudo.referencias.lgpd}</a></li><li><a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados/direito-dos-titulares" target="_blank" rel="noreferrer">{conteudo.referencias.anpd}</a></li></ul></section>
      <ContatoEmail compacto contexto={conteudo.titulo} />
    </article>
    <RodapePublico />
  </main>;
}
